// mrp-vue/src/features/songs/SongDetails.page.vue
<template>
  <div v-if="isLoading" class="flex justify-center p-8">
    <ProgressSpinner />
  </div>
  <div v-else-if="song" class="flex flex-col gap-4 p-4">
    <ConfirmDialog />
    <div class="flex justify-between">
      <CreateSongDialog
        v-if="song"
        v-model="isEditDialogVisible"
        :song="song"
        @refetchSongs="onEditSuccess"
      />
      <Button
        label="Home"
        icon="pi pi-home"
        class="p-button-outlined"
        @click="goHome"
      />

      <div class="flex gap-3">
        <Button
          v-if="isAdmin"
          label="Edit"
          icon="pi pi-pencil"
          class="p-button-outlined"
          severity="info"
          @click="onEditSong"
        />
        <Button
          v-if="isAdmin"
          label="Delete"
          icon="pi pi-trash"
          class="p-button-outlined"
          severity="danger"
          @click="onDeleteSong"
        />
        <Button
          label="Back"
          icon="pi pi-arrow-left"
          class="p-button-outlined"
          severity="secondary"
          @click="goBack"
        />
      </div>
    </div>

    <Card class="w-full">
      <template #content>
        <div class="flex gap-8">
          <div
            class="rounded-lg overflow-hidden w-[180px] h-[180px] shrink-0 bg-[#2a2a2a] flex items-center justify-center"
          >
            <Image
              v-if="displayImageUrl"
              :src="displayImageUrl"
              alt="Song Image"
              image-class="object-cover w-full h-full"
              class="w-full h-full"
            />
            <ProgressSpinner v-if="!displayImageUrl && isImageLoading" />
            <i
              v-else-if="!displayImageUrl"
              class="pi pi-image text-4xl text-gray-400"
            />
          </div>

          <div class="flex flex-col gap-4">
            <div class="flex flex-col gap-1">
              <h2 class="text-3xl font-bold m-0">{{ song.name }}</h2>
              <div class="flex items-center gap-2 text-gray-400 text-sm">
                <span class="flex items-center gap-1">
                  <i class="pi pi-calendar" /> {{ song.year }}
                </span>
                <span v-if="song.artists?.length">•</span>
                <span
                  v-if="song.artists?.length"
                  class="flex items-center gap-1"
                >
                  <i class="pi pi-user" />
                  {{ song.artists.map((a) => a.name).join(", ") }}
                </span>
              </div>
            </div>

            <div class="flex flex-col gap-4 justify-center items-center mt-4">
              <audio v-if="audioUrl" controls :src="audioUrl" @click.stop />
              <ProgressSpinner v-else-if="isAudioLoading" />
              <div v-else>
                <p class="text-gray-400 h-2rem text-sm italic">
                  No audio file available.
                </p>
              </div>
            </div>

            <div v-if="song.genres?.length">
              <h3 class="text-lg font-semibold mb-2">Genres</h3>
              <div class="flex flex-wrap gap-2">
                <Chip
                  v-for="genre in song.genres"
                  :key="genre.id"
                  :label="genre.name"
                />
              </div>
            </div>

            <div v-if="song.link">
              <Button
                label="Open External Link"
                icon="pi pi-external-link"
                @click="openLink(song.link)"
              />
            </div>
          </div>
        </div>
      </template>
    </Card>

    <Card v-if="song.albums?.length" class="w-full">
      <template #title>Albums</template>
      <template #content>
        <DataTable :value="song.albums" removableSort :row-hover="true" class="cursor-pointer" @row-click="(e) => router.push({ name: 'album-details', params: { id: e.data.id } })">
          <Column field="name" header="Name" sortable>
            <template #body="slotProps">
              <span
              >{{ slotProps.data.name }}</span>
            </template>
          </Column>
          <Column field="year" header="Year" sortable>
            <template #body="slotProps">
              <span
              >{{ slotProps.data.year }}</span>
            </template>
          </Column>
        </DataTable>
      </template>
    </Card>

    <Card class="w-full">
      <template #title>Reviews</template>
      <template #content>
        <DataTable
          v-if="songReviews?.content?.length"
          :value="songReviews.content"
          removableSort
        >
          <Column field="username" header="Reviewer" sortable />
          <Column field="grade" header="Rating" sortable>
            <template #body="slotProps">
              <Rating
                :model-value="slotProps.data.grade"
                readonly
                :cancel="false"
              />
            </template>
          </Column>
          <Column field="description" header="Description">
            <template #body="slotProps">
              <span class="line-clamp-2">{{ slotProps.data.description }}</span>
            </template>
          </Column>
          <Column field="creationDate" header="Created" sortable>
            <template #body="slotProps">
              {{ new Date(slotProps.data.creationDate).toLocaleDateString() }}
            </template>
          </Column>
          <Column field="type" header="Type" sortable>
            <template #body="slotProps">
              <Tag
                :value="'Song'"
                :severity="slotProps.data.type === 'SONG' ? 'success' : 'info'"
                rounded
              />
            </template>
          </Column>
        </DataTable>
        <div v-else class="text-gray-400">No reviews yet for this song.</div>
      </template>
    </Card>
  </div>
  <div v-else class="flex justify-center p-8">
    <p>Song not found.</p>
  </div>
</template>

<script setup lang="ts">
import {
  ProgressSpinner,
  Button,
  Card,
  Rating,
  Image,
  Chip,
  DataTable,
  Column,
  Tag,
  ConfirmDialog,
} from "primevue";
import { useConfirm } from "primevue/useconfirm";
import { useRoute, useRouter } from "vue-router";
import { computed, ref } from "vue";
import { useGetSong, useDeleteSong, CreateSongDialog, Role } from "@/features";
import { useGetFile, useAuthStore } from "@/shared";
import { storeToRefs } from "pinia";
import { useGetSongReviews } from "@/features/review";

const route = useRoute();
const router = useRouter();
const confirm = useConfirm();

const { user } = storeToRefs(useAuthStore());
const isAdmin = computed(() => user.value?.role === Role.ADMIN);

const songId = computed(() => {
  const id = route.params.id;
  return id ? Number(id) : undefined;
});

const {
  data: song,
  isLoading: isSongLoading,
  refetch: refetchSong,
} = useGetSong(songId);
const { data: songReviews, isLoading: isReviewsLoading } =
  useGetSongReviews(songId);

const { deleteSong } = useDeleteSong();

const isEditDialogVisible = ref(false);

const isLoading = computed(() => isSongLoading.value || isReviewsLoading.value);

const { fileUrl: displayImageUrl, isLoading: isImageLoading } = useGetFile(
  computed(() => song.value?.imageUrl),
);

const { fileUrl: audioUrl, isLoading: isAudioLoading } = useGetFile(
  computed(() => song.value?.fileUrl),
);

const goHome = () => router.push("/");
const goBack = () => router.go(-1);
const openLink = (link: string) => window.open(link, "_blank");

const onEditSong = () => {
  isEditDialogVisible.value = true;
};

const onEditSuccess = () => {
  refetchSong();
};

const onDeleteSong = () => {
  if (!songId.value) return;

  confirm.require({
    message: `Are you sure you want to delete "${song.value?.name}"?`,
    header: "Confirmation",
    icon: "pi pi-exclamation-triangle",
    rejectProps: {
      label: "Cancel",
      severity: "secondary",
      outlined: true,
    },
    acceptProps: {
      label: "Delete",
      severity: "danger",
    },
    accept: async () => {
      try {
        await deleteSong(songId.value!);
        router.push("/");
      } catch (error) {
        console.error("Error deleting song:", error);
      }
    },
  });
};
</script>

// mrp-react/src/features/songs/SongDetails.page.tsx
import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";

import { Card } from "primereact/card";
import { Image } from "primereact/image";
import { Chip } from "primereact/chip";
import { Button } from "primereact/button";
import { Divider } from "primereact/divider";
import { Message } from "primereact/message";
import { ProgressSpinner } from "primereact/progressspinner";
import {
  DataTable,
  DataTablePageEvent,
  DataTableStateEvent,
} from "primereact/datatable";
import { Column } from "primereact/column";
import { Rating } from "primereact/rating";
import { Tag } from "primereact/tag";

import ReviewDialog from "../../features/review/ReviewDialog.tsx";
import { useGetSong } from "../../shared/hooks/useGetSong.ts";
import { useGetImage } from "../../shared/hooks/useGetImage.ts";
import { useGetSongReviews } from "../../shared/hooks/useGetSongReviews.ts";
import {
  ArtistType,
  GenreType,
  ReviewResponse,
  UserRoleEnum,
} from "@shared/utils";
import { useCurrentUser } from "../../shared/hooks/useCurrentUser.ts";
import { deleteSong } from "./utils/helpers.tsx";
import CreateSongDialog from "./CreateSongDialog.tsx";
import { useSongAudio } from "../../shared/hooks/useSongAudio.ts";
import { ConfirmDialog, confirmDialog } from "primereact/confirmdialog";
import { toast } from "../../shared/components/ToastContext.tsx";
const VITE_BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

export default function SongDetailsPage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const songId = useMemo(() => (id ? Number(id) : undefined), [id]);
  const {
    song,
    loading: loadingSong,
    error: songError,
    refetch: songRefetch,
  } = useGetSong(songId);
  const {
    exists: audioExists,
    loading: loadingAudio,
    url: audioUrl,
    audioAsJsFile,
  } = useSongAudio(song?.id ?? -1, song?.fileUrl);
  const {
    loading: loadingImage,
    exists: imageExists,
    image: imageSrc,
    imageAsJsFile,
    refetch: refetchImage,
  } = useGetImage(
    songId ? `${VITE_BACKEND_URL}/images/song/${songId}` : undefined,
  );
  const {
    reviews,
    total,
    page,
    rows,
    loading: loadingReviews,
    error: reviewsError,
    sortField,
    sortOrder,
    onPage,
    onSort,
    refresh,
  } = useGetSongReviews(songId);
  const { user } = useCurrentUser();

  const [dialogVisible, setDialogVisible] = useState(false);
  const [deleting, setDeleting] = useState<boolean>(false);
  const [selectedReviewId, setSelectedReviewId] = useState<
    number | undefined
  >();
  const [editSongDialogVisible, setEditSongDialogVisible] =
    useState<boolean>(false);

  const openDialog = (row: ReviewResponse) => {
    setSelectedReviewId(row.id);
    setDialogVisible(true);
  };
  const closeDialog = () => setDialogVisible(false);

  const handlePage = (e: DataTablePageEvent) => {
    onPage({ first: e.first, rows: e.rows, page: e.page });
  };

  const handleSort = (e: DataTableStateEvent) => {
    const normalized: 1 | -1 | undefined =
      e.sortOrder === 1 ? 1 : e.sortOrder === -1 ? -1 : undefined;

    onSort({
      sortField: e.sortField ?? undefined,
      sortOrder: normalized,
    });
  };

  const handleDelete = () => {
    confirmDialog({
      header: "Confirm Delete",
      message: "Delete this song permanently?",
      icon: "pi pi-exclamation-triangle",
      acceptLabel: "Delete",
      rejectLabel: "Cancel",
      acceptClassName: "p-button-danger",
      accept: async () => {
        try {
          setDeleting(true);
          await deleteSong(song?.id ?? -1).then(() => navigate("/songs"));
          toast.success("Song deleted.");
        } catch {
          toast.error("Failed to delete song.");
        } finally {
          setDeleting(false);
        }
      },
    });
  };

  if (!songId) {
    return <Message severity="error" text="Invalid song id." />;
  }

  if (loadingSong) {
    return (
      <div className="min-h-[40vh] flex items-center justify-center gap-3 flex-col">
        <ProgressSpinner />
        <div className="text-[#6b7280] text-[0.95rem]">Loading song…</div>
      </div>
    );
  }

  if (songError || !song) {
    return <Message severity="error" text={songError ?? "Song not found."} />;
  }

  const canModify = !!user && user?.role === UserRoleEnum.ADMIN;

  const handleRefetch = () => {
    refetchImage?.();
    songRefetch?.();
  };

  return (
    <div className="p-3">
      <div className="flex justify-between">
        <div>
          <Button
            label="Home"
            icon="pi pi-home"
            onClick={() => navigate("/")}
            severity="secondary"
            outlined
          />
        </div>
        <div className="flex justify-end mb-3 gap-3">
          {canModify && (
            <div className="flex gap-3">
              <Button
                label="Edit"
                icon="pi pi-pencil"
                onClick={() => setEditSongDialogVisible(true)}
                severity="info"
                outlined
              />
              <Button
                label="Delete"
                icon={deleting ? "pi pi-spin pi-spinner" : "pi pi-trash"}
                onClick={handleDelete}
                severity="danger"
                outlined
              />
            </div>
          )}
          <Button
            label="Back"
            icon="pi pi-arrow-left"
            onClick={() => navigate(-1)}
            severity="secondary"
            outlined
          />
        </div>
      </div>

      <Card className="shadow-md" style={{ overflow: "hidden", borderRadius: 12 }}>
        <div className="flex gap-4 flex-col md:flex-row">
          <div style={{ width: 300, maxWidth: "100%" }}>
            {loadingImage ? (
              <div className="flex items-center justify-center">
                <i className="pi pi-spin pi-spinner" />
              </div>
            ) : (
              <Image
                src={imageExists && imageSrc ? imageSrc : undefined}
                imageStyle={{ width: "100%", objectFit: "cover" }}
              />
            )}
          </div>

          <div className="flex-1">
            <div className="text-2xl font-semibold mb-2">{song.name}</div>

            {Array.isArray(song.artists) && song.artists.length > 0 && (
              <div className="flex items-center gap-2 mb-2 flex-wrap">
                <i className="pi pi-user text-gray-500" />
                {song.artists.map((a: ArtistType, i) => (
                  <span key={a.id} className="flex items-center gap-2">
                    <span
                      className="cursor-pointer text-[0.95rem] hover:underline"
                      onClick={() => navigate(`/artist/${a.id}`)}
                    >
                      {a.name}
                    </span>
                    {i < song.artists!.length - 1 && <span className="text-gray-400">·</span>}
                  </span>
                ))}
              </div>
            )}

            {song.year ? (
              <div className="text-gray-500 mb-2">Released {song.year}</div>
            ) : null}

            {Array.isArray(song.genres) && song.genres.length > 0 && (
              <div className="flex gap-2 flex-wrap mb-3">
                {song.genres.map((g: GenreType) => (
                  <Chip key={g.id ?? g.name} label={g.name} className="text-[0.85rem]" />
                ))}
              </div>
            )}

            <div className="flex gap-5 flex-wrap">
              {song.link && (
                <Button
                  label="Open Song Link"
                  icon="pi pi-external-link"
                  onClick={() => window.open(song.link, "_blank")}
                />
              )}
              <div className="flex">
                {loadingAudio ? (
                  <i className="pi pi-spin pi-spinner" />
                ) : audioExists && audioUrl ? (
                  <audio controls src={audioUrl} className="my-auto" />
                ) : (
                  <div className="my-auto">
                    <p>No audio file available.</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </Card>

      <Divider />

      <Card>
        <div className="flex items-center justify-between mb-2">
          <h2 className="m-0">Albums</h2>
        </div>

        <DataTable
          value={song.albums ?? []}
          rowHover
          stripedRows
          removableSort
          paginator
          rows={10}
          emptyMessage="No albums for this song."
        >
          <Column field="name" header="Name" sortable />
          <Column field="year" header="Year" sortable />
        </DataTable>
      </Card>

      <Divider />

      <Card>
        <div className="flex items-center justify-between mb-2">
          <h2 className="m-0">Reviews</h2>
          {reviewsError && <Message severity="error" text={reviewsError} />}
        </div>

        <DataTable
          value={reviews}
          rowHover
          stripedRows
          removableSort
          sortMode="multiple"
          paginator
          lazy
          totalRecords={total}
          rows={rows}
          first={page * rows}
          loading={loadingReviews}
          emptyMessage="No reviews for this song yet."
          onPage={handlePage}
          onSort={handleSort}
          sortField={sortField}
          sortOrder={sortOrder as 1 | 0 | -1 | null | undefined}
          onRowClick={(e) => openDialog(e.data as ReviewResponse)}
          rowClassName={() => ({ "cursor-pointer": true })}
        >
          <Column
            field="username"
            header="Reviewer"
            body={(row: ReviewResponse) => <strong>{row.username}</strong>}
            sortable
          />
          <Column
            field="grade"
            header="Rating"
            body={(row: ReviewResponse) => (
              <Rating value={row.grade} readOnly cancel={false} />
            )}
            sortable
          />
          <Column field="description" header="Description" />
          <Column
            field="creationDate"
            header="Created"
            body={(row: ReviewResponse) =>
              new Date(row.creationDate).toLocaleDateString("hr-HR")
            }
            sortable
          />
          <Column
            header="Type"
            body={() => <Tag value="Song" severity="success" />}
          />
        </DataTable>
      </Card>

      {dialogVisible && selectedReviewId !== undefined && (
        <ReviewDialog
          key={selectedReviewId}
          visible={dialogVisible}
          onHide={closeDialog}
          reviewId={selectedReviewId}
          reviewType="SONG"
          refetch={refresh}
        />
      )}

      {editSongDialogVisible && (
        <CreateSongDialog
          visible={editSongDialogVisible}
          setVisible={setEditSongDialogVisible}
          onCreated={handleRefetch}
          existingSongData={{
            songId,
            formData: {
              name: song.name,
              cover: imageExists && imageAsJsFile ? imageAsJsFile : undefined,
              file: audioExists && audioAsJsFile ? audioAsJsFile : undefined,
              year: song.year ?? undefined,
              link: song.link ?? undefined,
              albumIds: song.albums?.map((a) => a.id) ?? [],
              artistIds: song.artists?.map((a) => a.id) ?? [],
              genreIds: song.genres?.map((g) => g.id) ?? [],
            },
          }}
        />
      )}
      <ConfirmDialog />
    </div>
  );
}
