// mrp-react/src/features/songs/CreateSongDialog.tsx
import {
  Dispatch,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { Dialog } from "primereact/dialog";
import { toast } from "../../shared/components/ToastContext.tsx";
import {
  Controller,
  FormProvider,
  SubmitHandler,
  useForm,
} from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  SongCreateForm,
  songCreateSchema,
  SongRequestData,
  truncate,
} from "@shared/utils";
import { InputText } from "primereact/inputtext";
import { FileUpload, FileUploadSelectEvent } from "primereact/fileupload";
import { Button } from "primereact/button";
import { useGetArtists } from "../artists/hooks/useGetArtists.ts";
import CreateLimitedAlbumDialog from "../../shared/components/CreateLimitedAlbumDialog.tsx";
import CreateLimitedArtistDialog from "../../shared/components/CreateLimitedArtistDialog.tsx";
import AlbumMultiSelect from "../../shared/components/AlbumMultiSelect.tsx";
import ArtistMultiSelect, {
  ArtistOption,
} from "../../shared/components/ArtistMultiSelect.tsx";
import GenresMultiSelect from "../../shared/components/GenresMultiSelect.tsx";
import { createSong, updateSong } from "./utils/helpers.tsx";

interface Props {
  visible: boolean;
  setVisible: Dispatch<boolean>;
  onCreated: () => void;
  existingSongData?: SongRequestData; // expects arrays in formData
}

const EMPTY_FORM: SongCreateForm = {
  name: "",
  link: undefined,
  year: undefined,
  file: undefined,
  cover: undefined,
  albumIds: [],
  artistIds: [],
  genreIds: [],
};

export default function CreateSongDialog({
  visible,
  setVisible,
  onCreated,
  existingSongData,
}: Props) {
  const {
    artists,
    loading: artistsLoading,
    refetch: refetchArtists,
  } = useGetArtists();

  const [artistDialogVisible, setArtistDialogVisible] = useState(false);
  const [albumDialogVisible, setAlbumDialogVisible] = useState(false);

  const audioUploadRef = useRef<FileUpload>(null);
  const coverUploadRef = useRef<FileUpload>(null);
  const [audioName, setAudioName] = useState<string>("Choose");
  const [coverName, setCoverName] = useState<string>("Choose");

  const handleArtistCreated = useCallback(() => {
    refetchArtists?.();
    setArtistDialogVisible(false);
  }, [refetchArtists]);

  const handleAlbumCreated = useCallback(() => {
    setAlbumDialogVisible(false);
  }, []);

  const artistOptions: ArtistOption[] = useMemo(
    () => (artists as ArtistOption[]) ?? [],
    [artists],
  );

  const methods = useForm<SongCreateForm>({
    resolver: zodResolver(songCreateSchema),
    defaultValues: EMPTY_FORM,
  });

  const {
    handleSubmit,
    reset,
    control,
    formState: { errors, isSubmitting },
  } = methods;

  useEffect(() => {
    const nextDefaults: SongCreateForm = existingSongData
      ? {
          name: existingSongData.formData.name ?? "",
          link: existingSongData.formData.link ?? undefined,
          year: existingSongData.formData.year ?? undefined,
          file: undefined,
          cover: undefined,
          albumIds: existingSongData.formData.albumIds ?? [],
          artistIds: existingSongData.formData.artistIds ?? [],
          genreIds: existingSongData.formData.genreIds ?? [],
        }
      : EMPTY_FORM;

    reset(nextDefaults);

    setAudioName(
      existingSongData?.formData.file ? "Change Existing" : "Choose",
    );
    setCoverName(
      existingSongData?.formData.cover ? "Change Existing" : "Choose",
    );
  }, [existingSongData, visible, reset]);

  const onSubmit: SubmitHandler<SongCreateForm> = useCallback(
    async (data) => {
      try {
        if (existingSongData?.songId) {
          await updateSong({
            songId: existingSongData.songId,
            formData: data,
          });
          toast.success("Song updated.");
        } else {
          await createSong({ formData: data });
          toast.success("Song created.");
        }
        reset(EMPTY_FORM);
        onCreated();
        setVisible(false);
      } catch {
        toast.error(
          existingSongData?.songId
            ? "Failed to update song."
            : "Failed to create song.",
        );
      }
    },
    [existingSongData, onCreated, reset, setVisible],
  );

  return (
    <Dialog
      visible={visible}
      header={() =>
        existingSongData ? <div>Edit Song</div> : <div>Add a Song</div>
      }
      onHide={() => {
        reset(EMPTY_FORM);
        setVisible(false);
      }}
      resizable={false}
      draggable={false}
      className="md:w-[650px] w-[400px]"
    >
      <FormProvider {...methods}>
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="p-fluid flex flex-col gap-1"
        >
          <div className="field">
            <label htmlFor="name">Song Name</label>
            <Controller
              name="name"
              control={control}
              render={({ field }) => (
                <InputText
                  id="name"
                  value={field.value ?? ""}
                  onChange={(e) => field.onChange(e.target.value)}
                />
              )}
            />
            {errors.name && (
              <small className="p-error">{errors.name.message}</small>
            )}
          </div>

          <div className="flex justify-around gap-3">
            <div className="field">
              <label htmlFor="file">Audio File</label>
              <Controller
                name="file"
                control={control}
                render={({ field }) => (
                  <FileUpload
                    ref={audioUploadRef}
                    name={field.name}
                    mode="basic"
                    multiple={false}
                    customUpload
                    accept="audio/*"
                    maxFileSize={10_000_000}
                    chooseLabel={audioName}
                    chooseOptions={{
                      icon: existingSongData ? "pi pi-sync" : "pi pi-plus",
                    }}
                    onSelect={(event: FileUploadSelectEvent) => {
                      if (event.files && event.files.length) {
                        const f = event.files[0];
                        field.onChange(f);
                        setAudioName(truncate(f.name));
                        audioUploadRef.current?.clear();
                      }
                    }}
                  />
                )}
              />
              {errors.file && (
                <small className="p-error">{errors.file.message}</small>
              )}
            </div>

            <div className="field">
              <label htmlFor="cover">Cover Image</label>
              <Controller
                name="cover"
                control={control}
                render={({ field }) => (
                  <FileUpload
                    ref={coverUploadRef}
                    name={field.name}
                    mode="basic"
                    customUpload
                    accept="image/*"
                    maxFileSize={5_000_000}
                    chooseLabel={coverName}
                    chooseOptions={{
                      icon: existingSongData ? "pi pi-sync" : "pi pi-plus",
                    }}
                    onSelect={(event: FileUploadSelectEvent) => {
                      if (event.files && event.files.length) {
                        const f = event.files[0];
                        field.onChange(f);
                        setCoverName(truncate(f.name));
                        coverUploadRef.current?.clear();
                      }
                    }}
                  />
                )}
              />
              {errors.cover && (
                <small className="p-error">{errors.cover.message}</small>
              )}
            </div>
          </div>

          <div className="field">
            <label htmlFor="link">Link to song</label>
            <Controller
              name="link"
              control={control}
              render={({ field }) => (
                <InputText
                  id="link"
                  value={field.value ?? ""}
                  onChange={(e) => field.onChange(e.target.value)}
                />
              )}
            />
            {errors.link && (
              <small className="p-error">{errors.link.message}</small>
            )}
          </div>

          <div className="field">
            <label htmlFor="year">Year</label>
            <Controller
              name="year"
              control={control}
              render={({ field }) => (
                <InputText
                  id="year"
                  type="number"
                  value={field.value !== undefined ? String(field.value) : ""}
                  onChange={(e) => {
                    const v = e.target.value;
                    field.onChange(v === "" ? undefined : Number(v));
                  }}
                  onBlur={field.onBlur}
                  name={field.name}
                  ref={field.ref}
                />
              )}
            />
            {errors.year && (
              <small className="p-error">{errors.year.message}</small>
            )}
          </div>

          <div className="field">
            <label htmlFor="genreIdsSelect">Genres (optional)</label>
            <Controller
              name="genreIds"
              control={control}
              render={({ field }) => (
                <GenresMultiSelect
                  value={field.value ?? []}
                  onChange={(ids) => field.onChange(ids)}
                  allowCreate
                  appendTo={
                    typeof document !== "undefined" ? document.body : undefined
                  }
                  className="w-full"
                />
              )}
            />
          </div>

          <div className="field">
            <label htmlFor="albumIdsSelect">Albums (optional)</label>
            <Controller
              name="albumIds"
              control={control}
              render={({ field }) => (
                <AlbumMultiSelect
                  value={field.value ?? []}
                  onChange={(ids) => field.onChange(ids)}
                  onCreateNew={() => setAlbumDialogVisible(true)}
                  appendTo={
                    typeof document !== "undefined" ? document.body : undefined
                  }
                  className="w-full"
                />
              )}
            />
          </div>

          <div className="field mb-3">
            <label htmlFor="artistIdsSelect">Artists (optional)</label>
            <Controller
              name="artistIds"
              control={control}
              render={({ field }) => (
                <ArtistMultiSelect
                  value={field.value ?? []}
                  options={artistOptions}
                  loading={artistsLoading}
                  onChange={(ids) => field.onChange(ids)}
                  onCreateNew={() => setArtistDialogVisible(true)}
                  appendTo={
                    typeof document !== "undefined" ? document.body : undefined
                  }
                  className="w-full"
                />
              )}
            />
          </div>

          <Button type="submit" label="Submit" loading={isSubmitting} />
        </form>
      </FormProvider>

      <CreateLimitedAlbumDialog
        visible={albumDialogVisible}
        setVisible={setAlbumDialogVisible}
        onCreated={handleAlbumCreated}
      />
      <CreateLimitedArtistDialog
        visible={artistDialogVisible}
        setVisible={setArtistDialogVisible}
        onCreated={handleArtistCreated}
      />
    </Dialog>
  );
}

// mrp-vue/src/features/songs/CreateSongDialog.vue
<script setup lang="ts">
import { Button, Dialog, InputText, FileUpload, InputNumber, useToast } from "primevue";
import { useForm } from "vee-validate";
import { ModifiedMultiSelect } from "@/shared/components";
import { toTypedSchema } from "@vee-validate/zod";
import {
  type MultiSelectOptionType,
  songCreateDefaultValues,
  songCreateSchema,
  type SongResponse,
  useGetAllGenres,
} from "@/shared";
import { useCreateSong, useUpdateSong } from "@/features";
import { computed } from "vue";

const isDialogVisible = defineModel<boolean>();

const props = defineProps<{
  song?: SongResponse;
}>();

const emit = defineEmits<{
  (e: "refetchSongs"): void;
}>();

const toast = useToast();
const { createSong, isLoading: isCreating } = useCreateSong();
const { updateSong, isLoading: isUpdating } = useUpdateSong();
const { data: genres, isLoading: isGenresLoading } = useGetAllGenres();

const isSubmitting = computed(() => isCreating.value || isUpdating.value);

const genreOptions = computed<MultiSelectOptionType[]>(() => {
  return (
    genres.value?.map((genre) => ({
      label: genre.name,
      value: genre.id,
    })) || []
  );
});

const validationSchema = toTypedSchema(songCreateSchema);

const initialValues = computed(() => {
  if (props.song) {
    return {
      name: props.song.name,
      year: props.song.year,
      link: props.song.link,
      genreIds: props.song.genres?.map((g) => g.id) || [],
      albumIds: props.song.albums?.map((a) => a.id) || [],
      artistIds: props.song.artists?.map((a) => a.id) || [],
      cover: undefined,
      file: undefined,
    };
  }
  return songCreateDefaultValues;
});

const { handleSubmit, defineField, errors, resetForm } = useForm({
  validationSchema,
  initialValues: initialValues.value,
  keepValuesOnUnmount: false,
});

// Watch initialValues and reset form when they change
import { watch } from "vue";
watch(
  initialValues,
  (newValues) => {
    resetForm({ values: newValues });
  },
  { immediate: true },
);

const [name] = defineField("name");
const [link] = defineField("link");
const [year] = defineField("year");
const [file] = defineField("file");
const [cover] = defineField("cover");
const [genreIds] = defineField("genreIds");
const [albumIds] = defineField("albumIds");
const [artistIds] = defineField("artistIds");

const onSubmit = handleSubmit(async (values) => {
  let result;
  if (props.song) {
    result = await updateSong(props.song.id, values);
  } else {
    result = await createSong(values);
  }

  if (result) {
    toast.add({ severity: "success", summary: props.song ? "Song updated successfully" : "Song added successfully" });
    isDialogVisible.value = false;
    emit("refetchSongs");
  }
});
</script>

<template>
  <Dialog
    modal
    class="w-160"
    v-model:visible="isDialogVisible"
    :header="props.song ? 'Edit song' : 'Add a song'"
    :draggable="false"
  >
    <form @submit="onSubmit" class="flex flex-col gap-3 w-full">
      <div class="flex flex-col gap-2">
        <label>Song Name</label>
        <InputText v-model="name" type="text" :invalid="!!errors.name" />
        <small v-if="errors.name" class="text-red-500">{{ errors.name }}</small>
      </div>

      <div class="flex flex-col w-fit gap-3">
        <div class="flex flex-col gap-2">
          <label for="file">Audio File</label>
          <FileUpload
            label="Choose"
            mode="basic"
            icon="pi pi-plus"
            accept="audio/*"
            :invalid="!!errors.file"
            @select="(e) => (file = e.files[0])"
          />
          <small v-if="errors.file" class="text-red-500">{{
            errors.file
          }}</small>
        </div>

        <div class="flex flex-col gap-2">
          <label for="cover">Cover Image</label>
          <FileUpload
            label="Choose"
            mode="basic"
            icon="pi pi-plus"
            accept="image/*"
            :invalid="!!errors.cover"
            @select="(e) => (cover = e.files[0])"
          />
          <small v-if="errors.cover" class="text-red-500">{{
            errors.cover
          }}</small>
        </div>
      </div>

      <div class="flex flex-col gap-2">
        <label for="link">Link to song</label>
        <InputText
          id="link"
          v-model="link"
          type="text"
          :invalid="!!errors.link"
        />
        <small v-if="errors.link" class="text-red-500">{{ errors.link }}</small>
      </div>

      <div class="flex flex-col gap-2">
        <label for="year">Year</label>
        <InputNumber
          id="year"
          v-model="year"
          :use-grouping="false"
          :invalid="!!errors.year"
        />
        <small v-if="errors.year" class="text-red-500">{{ errors.year }}</small>
      </div>

      <div class="flex flex-col gap-2">
        <label>Genres (optional)</label>
        <ModifiedMultiSelect
          :options="genreOptions"
          :loading="isGenresLoading"
          v-model="genreIds"
          :invalid="!!errors.genreIds"
        />
        <small v-if="errors.genreIds" class="text-red-500">{{
          errors.genreIds
        }}</small>
      </div>

      <div class="flex flex-col gap-2">
        <label>Albums (optional)</label>
        <ModifiedMultiSelect
          :options="[]"
          v-model="albumIds"
          :invalid="!!errors.albumIds"
        />
        <small v-if="errors.albumIds" class="text-red-500">{{
          errors.albumIds
        }}</small>
      </div>

      <div class="flex flex-col gap-2">
        <label>Artists (optional)</label>
        <ModifiedMultiSelect
          :options="[]"
          v-model="artistIds"
          :invalid="!!errors.artistIds"
        />
        <small v-if="errors.artistIds" class="text-red-500">{{
          errors.artistIds
        }}</small>
      </div>

      <div class="flex flex-col gap-2 w-full items-end">
        <Button
          type="submit"
          :label="props.song ? 'Update song' : 'Add new song'"
          :icon="props.song ? 'pi pi-check' : 'pi pi-plus'"
          :loading="isSubmitting"
        />
      </div>
    </form>
  </Dialog>
</template>
