// mrp-react/src/features/songs/Songs.page.tsx
import { useGetSongs } from "./hooks/useGetSongs.tsx";
import { Button } from "primereact/button";
import { ProgressSpinner } from "primereact/progressspinner";
import { Message } from "primereact/message";
import { InputText } from "primereact/inputtext";
import { IconField } from "primereact/iconfield";
import { InputIcon } from "primereact/inputicon";
import CreateSongDialog from "./CreateSongDialog.tsx";
import SongFilterPanel from "./SongFilterPanel.tsx";
import { useState, useEffect, useRef } from "react";
import SongCard from "../../shared/components/SongCard.tsx";
import { useCurrentUser } from "../../shared/hooks/useCurrentUser.ts";
import { UserRoleEnum } from "@shared/utils";

export default function SongsPage() {
  const {
    songs,
    loading,
    loadingMore,
    error,
    refetch,
    search,
    filters,
    hasActiveFilters,
    onSearchChange,
    onFiltersChange,
    clearSearch,
    clearFilters,
    hasMore,
    loadMore,
  } = useGetSongs();
  const { user } = useCurrentUser();
  const [visibleDialog, setVisibleDialog] = useState<boolean>(false);
  const sentinelRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!hasMore || loadingMore) return;
    const el = sentinelRef.current;
    if (!el) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) loadMore();
      },
      { threshold: 0.1 },
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [hasMore, loadingMore, loadMore]);

  if (error) {
    return (
      <div className="min-h-[40vh] flex items-center justify-center gap-3 flex-col">
        <Message severity="error" text={`Error: ${error}`} />
        <Button label="Retry" icon="pi pi-refresh" onClick={refetch} className="mt-1" />
      </div>
    );
  }

  return (
    <>
      <div className="flex flex-col justify-center items-center gap-4">
        <div className="w-full flex items-center justify-center gap-3">
          {user?.role === UserRoleEnum.ADMIN && (
            <Button
              label="Add New Song"
              icon="pi pi-plus"
              className="w-[15rem] shrink-0"
              onClick={() => setVisibleDialog(true)}
            />
          )}

          <div className="flex gap-2 w-full max-w-md">
            <IconField iconPosition="left" className="flex-1">
              <InputIcon className="pi pi-search" />
              <InputText
                value={search}
                onChange={(e) => onSearchChange(e.target.value)}
                placeholder="Search songs…"
                className="w-full"
              />
            </IconField>
            {search.length > 0 && (
              <Button
                icon="pi pi-times"
                severity="secondary"
                outlined
                onClick={clearSearch}
                aria-label="Clear search"
              />
            )}
            <SongFilterPanel
              filters={filters}
              hasActiveFilters={hasActiveFilters}
              onChange={onFiltersChange}
              onClear={clearFilters}
            />
          </div>
        </div>

        {loading ? (
          <div className="min-h-[40vh] flex items-center justify-center gap-3 flex-col">
            <ProgressSpinner />
            <div className="text-[#6b7280] text-[0.95rem]">Loading…</div>
          </div>
        ) : (
          <>
            <div className="flex flex-wrap gap-4 justify-center">
              {songs.map((song) => (
                <SongCard key={`song${song.id}`} song={song} refetch={refetch} />
              ))}

              {songs.length === 0 && (
                <div className="text-[#6b7280] text-[0.95rem]">No songs found.</div>
              )}
            </div>

            {hasMore && (
              <div ref={sentinelRef} className="w-full flex justify-center py-6">
                {loadingMore && <ProgressSpinner style={{ width: "2rem", height: "2rem" }} />}
              </div>
            )}
          </>
        )}
      </div>

      {visibleDialog && (
        <CreateSongDialog
          visible={visibleDialog}
          setVisible={setVisibleDialog}
          onCreated={refetch}
        />
      )}
    </>
  );
}

// mrp-vue/src/features/songs/Songs.page.vue
<template>
  <div class="flex flex-col gap-4 items-center">
    <div class="w-full flex items-center justify-center gap-3 flex-wrap">
      <Button
        v-if="user?.role === Role.ADMIN"
        label="Add New Song"
        icon="pi pi-plus"
        class="w-fit shrink-0"
        @click="isDialogVisible = true"
      />

      <div class="flex gap-2 w-full max-w-md">
        <IconField icon-position="left" class="flex-1">
          <InputIcon class="pi pi-search" />
          <InputText
            :value="search"
            placeholder="Search songs…"
            class="w-full"
            @input="(e) => onSearchChange((e.target as HTMLInputElement).value)"
          />
        </IconField>
        <Button
          v-if="search.length > 0"
          icon="pi pi-times"
          severity="secondary"
          outlined
          aria-label="Clear search"
          @click="clearSearch"
        />
        <SongFilterPanel
          :filters="filters"
          :has-active-filters="hasActiveFilters"
          @update:filters="onFiltersChange"
          @clear="clearFilters"
        />
      </div>
    </div>

    <div v-if="isLoading" class="flex justify-center items-center h-64">
      <ProgressSpinner />
    </div>

    <template v-else>
      <div
        :class="
          isMobile
            ? 'flex flex-wrap gap-2 justify-center'
            : 'flex flex-wrap gap-4 justify-center'
        "
      >
        <SongCard
          v-for="song in songs"
          :key="song.id"
          :song="song"
          @review="onReviewSong"
          @song-click="onSongClick"
        />
      </div>

      <div v-if="songs.length === 0" class="text-gray-500">No songs found.</div>

      <div ref="sentinelRef" class="w-full flex justify-center py-6">
        <ProgressSpinner v-if="isLoadingMore" style="width: 2rem; height: 2rem" />
      </div>
    </template>
  </div>

  <CreateSongDialog v-model="isDialogVisible" @refetchSongs="refetch" />

  <EditReviewDialog
    v-if="selectedSong"
    v-model:visible="isReviewDialogVisible"
    :name="selectedSong.name"
    review-type="SONG"
    :initial-values="{
      grade: 5,
      description: '',
      songId: selectedSong.id,
    }"
    @success="refetch"
  />
</template>

<script setup lang="ts">
import { useAuthStore } from "@/shared";
import { Button, ProgressSpinner, InputText, IconField, InputIcon } from "primevue";
import { CreateSongDialog, EditReviewDialog, Role, SongCard } from "@/features";
import { storeToRefs } from "pinia";
import { ref, onMounted, onUnmounted, watch } from "vue";
import { useRouter } from "vue-router";
import { useGetSongs } from "./hooks/useGetSongs";
import SongFilterPanel from "./SongFilterPanel.vue";
import type { SongResponse } from "@/shared";
import { useMediaQuery } from "@vueuse/core";

const authStore = useAuthStore();
const { user } = storeToRefs(authStore);

const {
  songs,
  isLoading,
  isLoadingMore,
  search,
  filters,
  hasActiveFilters,
  hasMore,
  onSearchChange,
  onFiltersChange,
  clearSearch,
  clearFilters,
  loadMore,
  refetch,
} = useGetSongs();

const router = useRouter();
const isMobile = useMediaQuery("(max-width: 850px)");

const isDialogVisible = ref(false);
const isReviewDialogVisible = ref(false);
const selectedSong = ref<SongResponse | null>(null);
const sentinelRef = ref<HTMLDivElement | null>(null);

let observer: IntersectionObserver | null = null;

const setupObserver = () => {
  if (observer) observer.disconnect();
  if (!sentinelRef.value || !hasMore.value || isLoadingMore.value) return;
  observer = new IntersectionObserver(
    (entries) => {
      if (entries[0]?.isIntersecting) loadMore();
    },
    { threshold: 0.1 },
  );
  observer.observe(sentinelRef.value);
};

onMounted(() => {
  watch([hasMore, isLoadingMore, sentinelRef], setupObserver, { immediate: true });
});

onUnmounted(() => observer?.disconnect());

const onReviewSong = (song: SongResponse) => {
  selectedSong.value = song;
  isReviewDialogVisible.value = true;
};

const onSongClick = (song: SongResponse) => {
  router.push(`/song/${song.id}`);
};
</script>
