// mrp-react/src/features/artists/Artists.page.tsx
import { useState, useEffect, useRef } from "react";
import { Button } from "primereact/button";
import { ProgressSpinner } from "primereact/progressspinner";
import { Message } from "primereact/message";
import { InputText } from "primereact/inputtext";
import { IconField } from "primereact/iconfield";
import { InputIcon } from "primereact/inputicon";

import { useGetArtists } from "./hooks/useGetArtists.ts";
import CreateArtistDialog from "./CreateArtistDialog.tsx";
import ArtistCard from "../../shared/components/ArtistCard.tsx";
import ArtistFilterPanel from "./ArtistFilterPanel.tsx";
import { useCurrentUser } from "../../shared/hooks/useCurrentUser.ts";
import { UserRoleEnum } from "@shared/utils";

export default function ArtistsPage() {
  const {
    artists,
    loading,
    loadingMore,
    error,
    refetch,
    search,
    filters,
    hasActiveFilters,
    onSearchChange,
    onFiltersChange,
    clearSearch,
    clearFilters,
    hasMore,
    loadMore,
  } = useGetArtists();
  const { user } = useCurrentUser();
  const [visibleDialog, setVisibleDialog] = useState<boolean>(false);
  const sentinelRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!hasMore || loadingMore) return;
    const el = sentinelRef.current;
    if (!el) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) loadMore();
      },
      { threshold: 0.1 },
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [hasMore, loadingMore, loadMore]);

  if (error) {
    return (
      <div className="min-h-[40vh] flex items-center justify-center gap-3 flex-col">
        <Message severity="error" text={`Error: ${error}`} />
        <Button label="Retry" icon="pi pi-refresh" onClick={refetch} className="mt-1" />
      </div>
    );
  }

  return (
    <>
      <div className="flex flex-col justify-center items-center gap-4 w-full">
        <div className="w-full flex items-center justify-center gap-3">
          {user?.role === UserRoleEnum.ADMIN && (
            <Button
              label="Add New Artist"
              icon="pi pi-plus"
              className="w-[15rem] shrink-0"
              onClick={() => setVisibleDialog(true)}
            />
          )}

          <div className="flex gap-2 w-full max-w-md">
            <IconField iconPosition="left" className="flex-1">
              <InputIcon className="pi pi-search" />
              <InputText
                value={search}
                onChange={(e) => onSearchChange(e.target.value)}
                placeholder="Search artists…"
                className="w-full"
              />
            </IconField>
            {search.length > 0 && (
              <Button
                icon="pi pi-times"
                severity="secondary"
                outlined
                onClick={clearSearch}
                aria-label="Clear search"
              />
            )}
            <ArtistFilterPanel
              filters={filters}
              hasActiveFilters={hasActiveFilters}
              onChange={onFiltersChange}
              onClear={clearFilters}
            />
          </div>
        </div>

        {loading ? (
          <div className="min-h-[40vh] flex items-center justify-center gap-3 flex-col">
            <ProgressSpinner />
            <div className="text-[#6b7280] text-[0.95rem]">Loading…</div>
          </div>
        ) : (
          <>
            <div className="flex flex-wrap gap-4 justify-center w-full">
              {artists.map((artist) => (
                <ArtistCard key={`artist${artist.id}`} artist={artist} />
              ))}

              {artists.length === 0 && (
                <div className="text-[#6b7280] text-[0.95rem]">No artists found.</div>
              )}
            </div>

            {hasMore && (
              <div ref={sentinelRef} className="w-full flex justify-center py-6">
                {loadingMore && <ProgressSpinner style={{ width: "2rem", height: "2rem" }} />}
              </div>
            )}
          </>
        )}
      </div>

      {visibleDialog && (
        <CreateArtistDialog
          visible={visibleDialog}
          setVisible={setVisibleDialog}
          onCreated={refetch}
        />
      )}
    </>
  );
}

// mrp-vue/src/features/artists/Artists.page.vue
<template>
  <div class="flex flex-col gap-4 items-center">
    <div class="w-full flex items-center justify-center gap-3 flex-wrap">
      <Button
        v-if="user?.role === Role.ADMIN"
        label="Add New Artist"
        icon="pi pi-plus"
        class="w-fit shrink-0"
        @click="isDialogVisible = true"
      />

      <div class="flex gap-2 w-full max-w-md">
        <IconField icon-position="left" class="flex-1">
          <InputIcon class="pi pi-search" />
          <InputText
            :value="search"
            placeholder="Search artists…"
            class="w-full"
            @input="(e) => onSearchChange((e.target as HTMLInputElement).value)"
          />
        </IconField>
        <Button
          v-if="search.length > 0"
          icon="pi pi-times"
          severity="secondary"
          outlined
          aria-label="Clear search"
          @click="clearSearch"
        />
        <ArtistFilterPanel
          :filters="filters"
          :has-active-filters="hasActiveFilters"
          @update:filters="onFiltersChange"
          @clear="clearFilters"
        />
      </div>
    </div>

    <div v-if="isLoading" class="flex justify-center items-center h-64">
      <ProgressSpinner />
    </div>

    <template v-else>
      <div
        :class="
          isMobile
            ? 'flex flex-wrap gap-2 justify-center'
            : 'flex flex-wrap gap-4 justify-center'
        "
      >
        <ArtistCard
          v-for="artist in artists"
          :key="artist.id"
          :artist="artist"
          @artist-click="onArtistClick"
        />
      </div>

      <div v-if="artists.length === 0" class="text-gray-500">No artists found.</div>

      <div ref="sentinelRef" class="w-full flex justify-center py-6">
        <ProgressSpinner v-if="isLoadingMore" style="width: 2rem; height: 2rem" />
      </div>
    </template>
  </div>

  <CreateArtistDialog v-model="isDialogVisible" @refetchArtists="refetch" />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from "vue";
import { useRouter } from "vue-router";
import { ProgressSpinner, Button, InputText, IconField, InputIcon } from "primevue";
import { useMediaQuery } from "@vueuse/core";
import { useAuthStore } from "@/shared";
import { storeToRefs } from "pinia";
import type { ArtistResponseDto } from "@/shared";
import ArtistCard from "./ArtistCard.vue";
import CreateArtistDialog from "./CreateArtistDialog.vue";
import ArtistFilterPanel from "./ArtistFilterPanel.vue";
import { useGetArtists } from "./hooks/useGetArtists";
import { Role } from "@/features";

const authStore = useAuthStore();
const { user } = storeToRefs(authStore);
const isMobile = useMediaQuery("(max-width: 850px)");

const {
  artists,
  isLoading,
  isLoadingMore,
  search,
  filters,
  hasActiveFilters,
  hasMore,
  onSearchChange,
  onFiltersChange,
  clearSearch,
  clearFilters,
  loadMore,
  refetch,
} = useGetArtists();

const router = useRouter();
const isDialogVisible = ref(false);
const sentinelRef = ref<HTMLDivElement | null>(null);

let observer: IntersectionObserver | null = null;

const setupObserver = () => {
  if (observer) observer.disconnect();
  if (!sentinelRef.value || !hasMore.value || isLoadingMore.value) return;
  observer = new IntersectionObserver(
    (entries) => {
      if (entries[0]?.isIntersecting) loadMore();
    },
    { threshold: 0.1 },
  );
  observer.observe(sentinelRef.value);
};

onMounted(() => {
  watch([hasMore, isLoadingMore, sentinelRef], setupObserver, { immediate: true });
});

onUnmounted(() => observer?.disconnect());

const onArtistClick = (artist: ArtistResponseDto) => {
  router.push(`/artist/${artist.id}`);
};
</script>
