// mrp-react/src/features/artists/CreateArtistDialog.tsx
import {
  Dispatch,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { Dialog } from "primereact/dialog";
import { toast } from "../../shared/components/ToastContext.tsx";
import {
  Controller,
  FormProvider,
  SubmitHandler,
  useForm,
} from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  ArtistCreateForm,
  artistCreateSchema,
  ArtistRequestData,
  truncate,
} from "@shared/utils";
import { InputText } from "primereact/inputtext";
import { InputTextarea } from "primereact/inputtextarea";
import { FileUpload, FileUploadSelectEvent } from "primereact/fileupload";
import { Button } from "primereact/button";

import { useGetSongs } from "../songs/hooks/useGetSongs.tsx";
import { useGetAlbumsAll } from "../albums/hooks/useGetAlbumsAll.ts";

import CreateLimitedSongDialog from "../../shared/components/CreateLimitedSongDialog.tsx";
import CreateLimitedAlbumDialog from "../../shared/components/CreateLimitedAlbumDialog.tsx";

import SongMultiSelect, {
  SongOption,
} from "../../shared/components/SongMultiSelect.tsx";
import AlbumMultiSelect, {
  AlbumOption,
} from "../../shared/components/AlbumMultiSelect.tsx";
import { createArtist, updateArtist } from "./utils/helpers.tsx";

interface Props {
  visible: boolean;
  setVisible: Dispatch<boolean>;
  onCreated: () => void;
  existingArtistData?: ArtistRequestData;
}

const EMPTY_FORM: ArtistCreateForm = {
  name: "",
  description: "",
  image: undefined,
  songIds: [],
  albumIds: [],
};

export default function CreateArtistDialog({
  visible,
  setVisible,
  onCreated,
  existingArtistData,
}: Props) {
  const { songs, loading: songsLoading, refetch: refetchSongs } = useGetSongs();
  const {
    albums,
    loading: albumsLoading,
    refetch: refetchAlbums,
  } = useGetAlbumsAll();

  const [songDialogVisible, setSongDialogVisible] = useState(false);
  const [albumDialogVisible, setAlbumDialogVisible] = useState(false);

  const coverUploadRef = useRef<FileUpload>(null);
  const [coverName, setCoverName] = useState<string>("Choose");

  const handleSongCreated = useCallback(() => {
    refetchSongs?.();
    setSongDialogVisible(false);
  }, [refetchSongs]);

  const handleAlbumCreated = useCallback(() => {
    refetchAlbums?.();
    setAlbumDialogVisible(false);
  }, [refetchAlbums]);

  const songOptions: SongOption[] = useMemo(
    () =>
      (songs ?? []).map((s) => ({
        id: s.id,
        name: s.name,
        year: s.year,
      })) as SongOption[],
    [songs],
  );

  const albumOptions: AlbumOption[] = useMemo(
    () => (albums as AlbumOption[]) ?? [],
    [albums],
  );

  const methods = useForm<ArtistCreateForm>({
    resolver: zodResolver(artistCreateSchema),
    defaultValues: EMPTY_FORM,
    shouldUnregister: false,
  });

  const {
    handleSubmit,
    reset,
    control,
    formState: { errors, isSubmitting },
  } = methods;

  useEffect(() => {
    const nextDefaults: ArtistCreateForm = existingArtistData
      ? {
          name: existingArtistData.formData.name ?? "",
          description: existingArtistData.formData.description ?? "",
          image: undefined,
          songIds: existingArtistData.formData.songIds ?? [],
          albumIds: existingArtistData.formData.albumIds ?? [],
        }
      : EMPTY_FORM;

    reset(nextDefaults);
    setCoverName(
      existingArtistData?.formData.image ? "Change Existing" : "Choose",
    );
  }, [existingArtistData, visible, reset]);

  const onSubmit: SubmitHandler<ArtistCreateForm> = useCallback(
    async (data) => {
      const normalized: ArtistCreateForm = {
        ...data,
        songIds: data.songIds ?? [],
        albumIds: data.albumIds ?? [],
      };

      try {
        if (existingArtistData?.artistId) {
          await updateArtist({
            artistId: existingArtistData.artistId,
            formData: normalized,
          });
          toast.success("Artist updated.");
        } else {
          await createArtist({ formData: normalized });
          toast.success("Artist created.");
        }
        onCreated();
        setVisible(false);
      } catch {
        toast.error(
          existingArtistData?.artistId
            ? "Failed to update artist."
            : "Failed to create artist.",
        );
      }
    },
    [onCreated, setVisible, existingArtistData],
  );

  return (
    <Dialog
      visible={visible}
      header={() =>
        existingArtistData ? <div>Edit Artist</div> : <div>Add an Artist</div>
      }
      onHide={() => {
        reset(EMPTY_FORM);
        setVisible(false);
      }}
      resizable={false}
      draggable={false}
      className="md:w-[650px] w-[400px]"
    >
      <FormProvider {...methods}>
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="p-fluid flex flex-col gap-2"
        >
          <div className="field">
            <label htmlFor="name">Artist Name</label>
            <Controller
              name="name"
              control={control}
              render={({ field }) => <InputText id="name" {...field} />}
            />
            {errors.name && (
              <small className="p-error">{errors.name.message}</small>
            )}
          </div>

          <div className="field">
            <label htmlFor="description">Description</label>
            <Controller
              name="description"
              control={control}
              render={({ field }) => (
                <InputTextarea
                  autoResize
                  id="description"
                  rows={4}
                  {...field}
                />
              )}
            />
            {errors.description && (
              <small className="p-error">{errors.description.message}</small>
            )}
          </div>

          <div className="field">
            <label htmlFor="image">Image</label>
            <Controller
              name="image"
              control={control}
              render={({ field }) => (
                <FileUpload
                  ref={coverUploadRef}
                  name={field.name}
                  mode="basic"
                  customUpload
                  accept="image/*"
                  maxFileSize={5_000_000}
                  chooseLabel={coverName}
                  chooseOptions={{
                    icon: existingArtistData ? "pi pi-sync" : "pi pi-plus",
                  }}
                  onSelect={(event: FileUploadSelectEvent) => {
                    if (event.files && event.files.length) {
                      const f = event.files[0];
                      field.onChange(f);
                      setCoverName(truncate(f.name));
                      coverUploadRef.current?.clear();
                    }
                  }}
                />
              )}
            />
          </div>

          <div className="field">
            <label htmlFor="songIdsSelect">Songs (optional)</label>
            <Controller
              name="songIds"
              control={control}
              render={({ field }) => (
                <SongMultiSelect
                  value={field.value ?? []}
                  options={songOptions}
                  loading={songsLoading}
                  onChange={(ids) => field.onChange(ids)}
                  onCreateNew={() => setSongDialogVisible(true)}
                  appendTo={
                    typeof document !== "undefined" ? document.body : undefined
                  }
                  className="w-full"
                />
              )}
            />
          </div>

          <div className="field">
            <label htmlFor="albumIdsSelect">Albums (optional)</label>
            <Controller
              name="albumIds"
              control={control}
              render={({ field }) => (
                <AlbumMultiSelect
                  value={field.value ?? []}
                  options={albumOptions}
                  loading={albumsLoading}
                  onChange={(ids) => field.onChange(ids)}
                  onCreateNew={() => setAlbumDialogVisible(true)}
                  appendTo={
                    typeof document !== "undefined" ? document.body : undefined
                  }
                  className="w-full"
                />
              )}
            />
          </div>

          <Button
            type="submit"
            label="Submit"
            className="mt-3"
            loading={isSubmitting}
          />
        </form>
      </FormProvider>

      <CreateLimitedSongDialog
        visible={songDialogVisible}
        setVisible={setSongDialogVisible}
        onCreated={handleSongCreated}
      />
      <CreateLimitedAlbumDialog
        visible={albumDialogVisible}
        setVisible={setAlbumDialogVisible}
        onCreated={handleAlbumCreated}
      />
    </Dialog>
  );
}

// mrp-vue/src/features/artists/CreateArtistDialog.vue
<script setup lang="ts">
import { Button, Dialog, InputText, FileUpload, Textarea, useToast } from "primevue";
import { useForm } from "vee-validate";
import { ModifiedMultiSelect } from "@/shared/components";
import { toTypedSchema } from "@vee-validate/zod";
import {
  type MultiSelectOptionType,
  artistCreateDefaultValues,
  artistCreateSchema,
  type ArtistResponseDto,
} from "@/shared";
import { useCreateArtist, useUpdateArtist, useGetAllSongs, useGetAllAlbums } from "@/features";
import { computed, watch } from "vue";

const isDialogVisible = defineModel<boolean>();

const props = defineProps<{
  artist?: ArtistResponseDto;
}>();

const emit = defineEmits<{
  (e: "refetchArtists"): void;
}>();

const toast = useToast();
const { createArtist, isLoading: isCreating } = useCreateArtist();
const { updateArtist, isLoading: isUpdating } = useUpdateArtist();
const { data: songsData, isLoading: isSongsLoading } = useGetAllSongs();
const { data: albumsData, isLoading: isAlbumsLoading } = useGetAllAlbums();

const isSubmitting = computed(() => isCreating.value || isUpdating.value);

const songOptions = computed<MultiSelectOptionType[]>(() => {
  return (
    songsData.value?.map((song) => ({
      label: song.name,
      value: song.id,
    })) || []
  );
});

const albumOptions = computed<MultiSelectOptionType[]>(() => {
  return (
    albumsData.value?.content.map((album) => ({
      label: album.name,
      value: album.id,
    })) || []
  );
});

const validationSchema = toTypedSchema(artistCreateSchema);

const initialValues = computed(() => {
  if (props.artist) {
    return {
      name: props.artist.name,
      description: props.artist.description,
      songIds: props.artist.songs?.map((s) => s.id) || [],
      albumIds: props.artist.albums?.map((a) => a.id) || [],
      image: undefined,
    };
  }
  return artistCreateDefaultValues;
});

const { handleSubmit, defineField, errors, resetForm } = useForm({
  validationSchema,
  initialValues: initialValues.value,
  keepValuesOnUnmount: false,
});

watch(
  initialValues,
  (newValues) => {
    resetForm({ values: newValues });
  },
  { immediate: true },
);

const [name] = defineField("name");
const [description] = defineField("description");
const [image] = defineField("image");
const [songIds] = defineField("songIds");
const [albumIds] = defineField("albumIds");

const onSubmit = handleSubmit(async (values) => {
  let result;
  if (props.artist) {
    result = await updateArtist(props.artist.id, values);
  } else {
    result = await createArtist(values);
  }

  if (result) {
    toast.add({ severity: "success", summary: props.artist ? "Artist updated successfully" : "Artist added successfully" });
    isDialogVisible.value = false;
    emit("refetchArtists");
  }
});
</script>

<template>
  <Dialog
    modal
    class="w-160"
    v-model:visible="isDialogVisible"
    :header="props.artist ? 'Edit artist' : 'Add an artist'"
    :draggable="false"
  >
    <form @submit="onSubmit" class="flex flex-col gap-3 w-full">
      <div class="flex flex-col gap-2">
        <label>Artist Name</label>
        <InputText v-model="name" type="text" :invalid="!!errors.name" />
        <small v-if="errors.name" class="text-red-500">{{ errors.name }}</small>
      </div>

      <div class="flex flex-col w-fit gap-3">
        <div class="flex flex-col gap-2">
          <label for="image">Artist Image</label>
          <FileUpload
            label="Choose"
            mode="basic"
            icon="pi pi-plus"
            accept="image/*"
            :invalid="!!errors.image"
            @select="(e) => (image = e.files[0])"
          />
          <small v-if="errors.image" class="text-red-500">{{ errors.image }}</small>
        </div>
      </div>

      <div class="flex flex-col gap-2">
        <label>Description (optional)</label>
        <Textarea v-model="description" rows="3" :invalid="!!errors.description" />
        <small v-if="errors.description" class="text-red-500">{{ errors.description }}</small>
      </div>

      <div class="flex flex-col gap-2">
        <label>Songs (optional)</label>
        <ModifiedMultiSelect
          :options="songOptions"
          :loading="isSongsLoading"
          v-model="songIds"
          :invalid="!!errors.songIds"
        />
        <small v-if="errors.songIds" class="text-red-500">{{ errors.songIds }}</small>
      </div>

      <div class="flex flex-col gap-2">
        <label>Albums (optional)</label>
        <ModifiedMultiSelect
          :options="albumOptions"
          :loading="isAlbumsLoading"
          v-model="albumIds"
          :invalid="!!errors.albumIds"
        />
        <small v-if="errors.albumIds" class="text-red-500">{{ errors.albumIds }}</small>
      </div>

      <div class="flex flex-col gap-2 w-full items-end">
        <Button
          type="submit"
          :label="props.artist ? 'Update artist' : 'Add new artist'"
          :icon="props.artist ? 'pi pi-check' : 'pi pi-plus'"
          :loading="isSubmitting"
        />
      </div>
    </form>
  </Dialog>
</template>
