// mrp-vue/src/features/login-register/Register.page.vue
<template>
  <div class="max-w-md mx-auto mt-20 p-6 border border-white/20 rounded shadow">
    <p class="text-2xl font-bold mb-4">Register</p>

    <form @submit="onSubmit" class="flex flex-col gap-4">
      <div class="flex flex-col gap-2">
        <label for="username">Username</label>
        <InputText id="username" v-model="username" type="text" />
        <span class="text-sm text-red-500">{{ errors.username }}</span>
      </div>

      <div class="flex flex-col gap-2">
        <label for="password">Password</label>
        <InputText id="password" v-model="password" type="password" />
        <span class="text-sm text-red-500">{{ errors.password }}</span>
      </div>

      <div class="flex flex-col gap-2">
        <label for="email">Email</label>
        <InputText id="email" v-model="email" type="email" />
        <span class="text-sm text-red-500">{{ errors.email }}</span>
      </div>

      <div class="flex flex-col gap-2">
        <label>Role</label>
        <div class="flex gap-3">
          <div class="flex gap-2 items-center">
            <RadioButton inputId="user" v-model="role" value="USER" />
            <label for="user">USER</label>
          </div>
          <div class="flex gap-2 items-center">
            <RadioButton inputId="admin" v-model="role" value="ADMIN" />
            <label for="admin">ADMIN</label>
          </div>
        </div>
        <span class="text-sm text-red-500">{{ errors.role }}</span>
      </div>

      <div class="flex flex-col gap-1">
        <Button type="submit" label="Register" class="font-bold" />
        <div class="flex gap-1.5 mt-2 text-sm">
          Already have an account?
          <p class="underline cursor-pointer" @click="navigateToLogin">Login here.</p>
        </div>
      </div>
    </form>
  </div>
</template>

<script setup>
import { useRouter } from "vue-router";
import { InputText, Button, RadioButton } from "primevue";
import { useField, useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import { z } from "zod";
import { useAuthStore } from "@/shared";

const router = useRouter();
const { register } = useAuthStore();

const validationSchema = toTypedSchema(
  z.object({
    username: z
      .string({ message: "Username is required." })
      .min(3, { message: "Username needs to be at least 3 characters." }),
    password: z
      .string({ message: "Password is required." })
      .min(3, { message: "Password needs to be at least 3 characters." }),
    email: z
      .string({ message: "Email is required." })
      .email({ message: "Enter a valid email." }),
    role: z.enum(["USER", "ADMIN"], {
      required_error: "Choose a role.",
    }),
  }),
);

const { handleSubmit, errors } = useForm({
  validationSchema,
  initialValues: {
    username: "",
    password: "",
    email: "",
    role: "USER",
  },
});

const { value: username } = useField("username");
const { value: password } = useField("password");
const { value: email } = useField("email");
const { value: role } = useField("role");

const onSubmit = handleSubmit((values) => {
  register(values);
});

function navigateToLogin() {
  router.push("/login");
}
</script>

// mrp-react/src/features/login-register/Register.page.tsx
// RegisterPage.tsx
import { useState } from "react";
import {
  Controller,
  FormProvider,
  SubmitHandler,
  useForm,
} from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { InputText } from "primereact/inputtext";
import { RadioButton } from "primereact/radiobutton";
import { Button } from "primereact/button";
import { jwtDecode } from "jwt-decode";
import {
  extractErrorMessage,
  RegisterForm,
  registerSchema,
} from "@shared/utils";
import { Link, useNavigate } from "react-router";

type JwtPayload = { exp?: number; sub?: string };

function isTokenExpired(token: string): boolean {
  try {
    const { exp } = jwtDecode<JwtPayload>(token);
    if (!exp) return true;
    return Date.now() >= exp * 1000 - 30_000;
  } catch {
    return true;
  }
}

export function RegisterPage() {
  const navigate = useNavigate();
  const [error, setError] = useState<string | null>(null);

  const methods = useForm<RegisterForm>({
    resolver: zodResolver(registerSchema),
    defaultValues: {
      username: "",
      password: "",
      email: "",
      role: "USER", // default role
    },
  });

  const {
    handleSubmit,
    control,
    formState: { errors, isSubmitting },
  } = methods;

  const onSubmit: SubmitHandler<RegisterForm> = async (data) => {
    setError(null);
    try {
      const res = await fetch("/api/auth/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          username: data.username,
          password: data.password,
          email: data.email,
          role: data.role, // <-- include Role enum
        }),
      });
      if (!res.ok) {
        const txt = await res.text();
        throw new Error(txt || res.statusText);
      }
      const body = await res.json();
      const token: string = body.token;
      if (!token || isTokenExpired(token)) throw new Error("Invalid token");

      localStorage.setItem("jwt", token);
      navigate("/");
    } catch (e: unknown) {
      setError(extractErrorMessage(e));
    }
  };

  return (
    <div className="max-w-md mx-auto mt-20 p-6 border rounded shadow">
      <h2 className="text-2xl mb-4">Register</h2>
      <FormProvider {...methods}>
        <form onSubmit={handleSubmit(onSubmit)} className="p-fluid space-y-4">
          <div className="field">
            <label htmlFor="username">Username</label>
            <Controller
              name="username"
              control={control}
              render={({ field }) => <InputText id="username" {...field} />}
            />
            {errors.username && (
              <small className="p-error">{errors.username.message}</small>
            )}
          </div>

          <div className="field">
            <label htmlFor="password">Password</label>
            <Controller
              name="password"
              control={control}
              render={({ field }) => (
                <InputText id="password" type="password" {...field} />
              )}
            />
            {errors.password && (
              <small className="p-error">{errors.password.message}</small>
            )}
          </div>

          <div className="field">
            <label htmlFor="email">Email</label>
            <Controller
              name="email"
              control={control}
              render={({ field }) => (
                <InputText id="email" type="email" {...field} />
              )}
            />
            {errors.email && (
              <small className="p-error">{errors.email.message}</small>
            )}
          </div>

          {/* Role selector */}
          <div className="field">
            <label className="block mb-2">Role</label>
            <div className="flex items-center gap-6">
              <Controller
                name="role"
                control={control}
                render={({ field }) => (
                  <>
                    <label className="flex items-center gap-2">
                      <RadioButton
                        inputId="role-user"
                        value="USER"
                        onChange={(e) => field.onChange(e.value)}
                        checked={field.value === "USER"}
                      />
                      <span>USER</span>
                    </label>
                    <label className="flex items-center gap-2">
                      <RadioButton
                        inputId="role-admin"
                        value="ADMIN"
                        onChange={(e) => field.onChange(e.value)}
                        checked={field.value === "ADMIN"}
                      />
                      <span>ADMIN</span>
                    </label>
                  </>
                )}
              />
            </div>
            {errors.role && (
              <small className="p-error">{errors.role.message}</small>
            )}
          </div>

          {error && <div className="error-text mb-2">{error}</div>}

          <Button type="submit" label="Register" disabled={isSubmitting} />

          <div className="mt-2 text-sm">
            Already have an account?{" "}
            <Link to="/login" className="text-blue-600 underline">
              Login here.
            </Link>
          </div>
        </form>
      </FormProvider>
    </div>
  );
}
