// mrp-vue/src/features/artists/ArtistDetails.page.vue
<template>
  <div v-if="isLoading" class="flex justify-center p-8">
    <ProgressSpinner />
  </div>
  <div v-else-if="artist" class="flex flex-col gap-4 p-4">
    <ConfirmDialog />
    <div class="flex justify-between">
      <CreateArtistDialog
        v-if="artist"
        v-model="isEditDialogVisible"
        :artist="artist"
        @refetchArtists="onEditSuccess"
      />
      <Button
        label="Home"
        icon="pi pi-home"
        class="p-button-outlined"
        @click="goHome"
      />

      <div class="flex gap-3">
        <Button
          v-if="isAdmin"
          label="Edit"
          icon="pi pi-pencil"
          class="p-button-outlined"
          severity="info"
          @click="isEditDialogVisible = true"
        />
        <Button
          v-if="isAdmin"
          label="Delete"
          icon="pi pi-trash"
          class="p-button-outlined"
          severity="danger"
          @click="onDeleteArtist"
        />
        <Button
          label="Back"
          icon="pi pi-arrow-left"
          class="p-button-outlined"
          severity="secondary"
          @click="goBack"
        />
      </div>
    </div>

    <Card class="w-full">
      <template #content>
        <div class="flex gap-8">
          <div
            class="rounded-lg overflow-hidden w-[180px] h-[180px] shrink-0 bg-[#2a2a2a] flex items-center justify-center"
          >
            <Image
              v-if="displayImageUrl"
              :src="displayImageUrl"
              alt="Artist Image"
              image-class="object-cover w-full h-full"
              class="w-full h-full"
            />
            <ProgressSpinner v-if="!displayImageUrl && isImageLoading" />
            <i
              v-else-if="!displayImageUrl"
              class="pi pi-user text-4xl text-gray-400"
            />
          </div>

          <div class="flex flex-col gap-4">
            <div class="flex flex-col gap-1">
              <h2 class="text-3xl font-bold m-0">{{ artist.name }}</h2>
              <div class="flex items-center gap-2 text-gray-400 text-sm">
                <span class="flex items-center gap-1">
                  <i class="pi pi-book" /> {{ artist.albums?.length || 0 }} albums
                </span>
                <span>•</span>
                <span class="flex items-center gap-1">
                  <i class="pi pi-headphones" /> {{ artist.songs?.length || 0 }} songs
                </span>
              </div>
            </div>

            <div v-if="artist.description">
              <p class="text-gray-300">{{ artist.description }}</p>
            </div>
          </div>
        </div>
      </template>
    </Card>

    <Card v-if="artist.songs?.length" class="w-full">
      <template #title>Songs</template>
      <template #content>
        <DataTable
          :value="artist.songs"
          row-hover
          class="cursor-pointer"
          @row-click="(e) => router.push(`/song/${e.data.id}`)"
        >
          <Column field="name" header="Name" sortable />
          <Column field="year" header="Year" sortable />
        </DataTable>
      </template>
    </Card>

    <Card v-if="artist.albums?.length" class="w-full">
      <template #title>Albums</template>
      <template #content>
        <DataTable
          :value="artist.albums"
          row-hover
          class="cursor-pointer"
          @row-click="(e) => router.push(`/album/${e.data.id}`)"
        >
          <Column field="name" header="Name" sortable />
        </DataTable>
      </template>
    </Card>
  </div>
  <div v-else class="flex justify-center p-8">
    <p>Artist not found.</p>
  </div>
</template>

<script setup lang="ts">
import {
  ProgressSpinner,
  Button,
  Card,
  Image,
  DataTable,
  Column,
  ConfirmDialog,
} from "primevue";
import { useConfirm } from "primevue/useconfirm";
import { useRoute, useRouter } from "vue-router";
import { computed, ref } from "vue";
import { useGetFile, useAuthStore } from "@/shared";
import { useGetArtist } from "./hooks/useGetArtist";
import { useDeleteArtist } from "./hooks/useDeleteArtist";
import CreateArtistDialog from "./CreateArtistDialog.vue";
import { Role } from "@/features";
import { storeToRefs } from "pinia";

const route = useRoute();
const router = useRouter();
const confirm = useConfirm();

const { user } = storeToRefs(useAuthStore());
const isAdmin = computed(() => user.value?.role === Role.ADMIN);

const artistId = computed(() => {
  const id = route.params.id;
  return id ? Number(id) : undefined;
});

const {
  data: artist,
  isLoading: isArtistLoading,
  refetch: refetchArtist,
} = useGetArtist(artistId);

const { deleteArtist } = useDeleteArtist();

const isEditDialogVisible = ref(false);
const isLoading = computed(() => isArtistLoading.value);

const { fileUrl: displayImageUrl, isLoading: isImageLoading } = useGetFile(
  computed(() => artist.value?.imageUrl),
);

const goHome = () => router.push("/");
const goBack = () => router.go(-1);

const onEditSuccess = () => {
  refetchArtist();
};

const onDeleteArtist = () => {
  if (!artistId.value) return;

  confirm.require({
    message: `Are you sure you want to delete "${artist.value?.name}"?`,
    header: "Confirmation",
    icon: "pi pi-exclamation-triangle",
    rejectProps: {
      label: "Cancel",
      severity: "secondary",
      outlined: true,
    },
    acceptProps: {
      label: "Delete",
      severity: "danger",
    },
    accept: async () => {
      try {
        await deleteArtist(artistId.value!);
        router.push("/artists");
      } catch (error) {
        console.error("Error deleting artist:", error);
      }
    },
  });
};
</script>

// mrp-react/src/features/artists/ArtistDetails.page.tsx
import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";

import { Card } from "primereact/card";
import { Image } from "primereact/image";
import { Button } from "primereact/button";
import { Divider } from "primereact/divider";
import { Message } from "primereact/message";
import { ProgressSpinner } from "primereact/progressspinner";
import { DataTable } from "primereact/datatable";
import { Column } from "primereact/column";

import { useGetImage } from "../../shared/hooks/useGetImage.ts";
import { AlbumType, SongType, UserRoleEnum } from "@shared/utils";
import { useGetArtist } from "./hooks/useGetArtist.ts";
import { useCurrentUser } from "../../shared/hooks/useCurrentUser.ts";
import { confirmDialog, ConfirmDialog } from "primereact/confirmdialog";
import { toast } from "../../shared/components/ToastContext.tsx";
import CreateArtistDialog from "./CreateArtistDialog.tsx";
import { deleteArtist } from "./utils/helpers.tsx";

export default function ArtistDetailsPage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const artistId = useMemo(() => (id ? Number(id) : undefined), [id]);
  const { user } = useCurrentUser();
  const {
    artist,
    loading: loadingArtist,
    error: artistError,
    refetch: artistRefetch,
  } = useGetArtist(artistId);
  const {
    loading: loadingImage,
    exists: imageExists,
    image: imageSrc,
    imageAsJsFile,
    refetch: refetchImage,
  } = useGetImage(artistId ? `/api/images/artist/${artistId}` : undefined);

  const [editArtistDialogVisible, setEditArtistDialogVisible] =
    useState<boolean>(false);
  const [deleting, setDeleting] = useState<boolean>(false);

  const handleDelete = () => {
    confirmDialog({
      header: "Confirm Delete",
      message: "Delete this artist permanently?",
      icon: "pi pi-exclamation-triangle",
      acceptLabel: "Delete",
      rejectLabel: "Cancel",
      acceptClassName: "p-button-danger",
      accept: async () => {
        try {
          setDeleting(true);
          await deleteArtist(artist?.id ?? -1).then(() => navigate("/artists"));
          toast.success("Artist deleted.");
        } catch {
          toast.error("Failed to delete artist.");
        } finally {
          setDeleting(false);
        }
      },
    });
  };

  const handleRefetch = () => {
    refetchImage?.();
    artistRefetch?.();
  };

  if (!artistId) {
    return <Message severity="error" text="Invalid artist id." />;
  }

  if (loadingArtist) {
    return (
      <div className="page-status">
        <ProgressSpinner />
        <div className="page-status__text">Loading artist…</div>
      </div>
    );
  }

  if (artistError || !artist) {
    return (
      <Message severity="error" text={artistError ?? "Artist not found."} />
    );
  }

  const canModify = !!user && user.role === UserRoleEnum.ADMIN;

  return (
    <div className="artist-details-page p-3">
      <div className="flex justify-content-between mb-3">
        <Button
          label="Home"
          icon="pi pi-home"
          onClick={() => navigate("/")}
          severity="secondary"
          outlined
        />
        <div className="flex gap-3">
          {canModify && (
            <div className="flex gap-3">
              <Button
                label="Edit"
                icon="pi pi-pencil"
                onClick={() => setEditArtistDialogVisible(true)}
                severity="info"
                outlined
              />
              <Button
                label="Delete"
                icon={deleting ? "pi pi-spin pi-spinner" : "pi pi-trash"}
                onClick={handleDelete}
                severity="danger"
                outlined
              />
            </div>
          )}
          <Button
            label="Back"
            icon="pi pi-arrow-left"
            onClick={() => navigate(-1)}
            severity="secondary"
            outlined
          />
        </div>
      </div>

      <Card
        className="p-shadow-2"
        style={{ overflow: "hidden", borderRadius: 12 }}
      >
        <div className="flex gap-4 flex-column md:flex-row">
          <div style={{ width: 300, maxWidth: "100%" }}>
            {loadingImage ? (
              <div
                className="placeholder flex align-items-center justify-content-center"
                style={{ height: 280 }}
              >
                <i className="pi pi-spin pi-spinner" />
              </div>
            ) : (
              <Image
                src={imageExists && imageSrc ? imageSrc : undefined}
                imageStyle={{ width: "100%", height: 280, objectFit: "cover" }}
              />
            )}
          </div>

          <div className="flex-1">
            <div className="text-2xl font-semibold mb-2">{artist.name}</div>

            {artist.description ? (
              <div className="mb-3" style={{ whiteSpace: "pre-wrap" }}>
                {artist.description}
              </div>
            ) : null}
          </div>
        </div>
      </Card>

      <Divider />

      <Card>
        <div className="flex align-items-center justify-content-between mb-2">
          <h2 className="m-0">Songs</h2>
        </div>

        <DataTable
          value={artist.songs ?? []}
          rowHover
          stripedRows
          removableSort
          paginator
          rows={10}
          onRowClick={(row) => navigate(`/song/${row.data.id}`)}
          emptyMessage="No songs for this artist."
        >
          <Column field="name" header="Title" sortable />
          <Column
            field="year"
            header="Year"
            body={(row: SongType) => row.year ?? "-"}
            sortable
          />
        </DataTable>
      </Card>

      <Divider />

      <Card>
        <div className="flex align-items-center justify-content-between mb-2">
          <h2 className="m-0">Albums</h2>
        </div>

        <DataTable
          value={artist.albums ?? []}
          rowHover
          stripedRows
          removableSort
          paginator
          rows={10}
          onRowClick={(row) => navigate(`/album/${row.data.id}`)}
          emptyMessage="No albums for this artist."
        >
          <Column field="name" header="Name" sortable />
          <Column
            field="year"
            header="Year"
            body={(row: AlbumType) => row.year ?? "-"}
            sortable
          />
        </DataTable>
      </Card>

      {editArtistDialogVisible && (
        <CreateArtistDialog
          visible={editArtistDialogVisible}
          setVisible={setEditArtistDialogVisible}
          onCreated={handleRefetch}
          existingArtistData={{
            artistId,
            formData: {
              name: artist.name,
              image: imageExists ? imageAsJsFile : undefined,
              description: artist.description,
            },
            songIds: artist.songs?.map((s) => s.id) ?? [],
            albumIds: artist.albums?.map((a) => a.id) ?? [],
          }}
        />
      )}

      <ConfirmDialog />
    </div>
  );
}
