// mrp-react/src/features/profile/Profile.page.tsx
import { useCurrentUser, useLogout } from "@shared/utils";
import { DataTable } from "primereact/datatable";
import { Column } from "primereact/column";
import { Rating } from "primereact/rating";
import { Tag } from "primereact/tag";
import { useNavigate } from "react-router";
import { ProfileInfo } from "./ProfileInfo";
import { Button } from "primereact/button";
import { useGetMyReviews } from "./hooks/useGetMyReviews.ts";

export default function ProfilePage() {
  const navigate = useNavigate();

  const {
    user,
    loading: userLoading,
    error: userError,
    refresh: refreshUser,
  } = useCurrentUser();
  const logout = useLogout();

  const {
    reviews,
    loading: reviewsLoading,
    error: reviewsError,
    refresh: refreshRatings,
  } = useGetMyReviews();

  if (userLoading || reviewsLoading) return <div>Loading...</div>;

  if (!user || userError) {
    return (
      <div>
        <div>Error: {userError}</div>
        <Button onClick={refreshUser}>Retry</Button>
      </div>
    );
  }

  if (reviewsError) {
    return (
      <div>
        <div>Error loading reviews: {reviewsError}</div>
        <Button onClick={refreshRatings}>Retry</Button>
      </div>
    );
  }

  return (
    <div>
      <ProfileInfo user={user} logout={logout} />

      <h1>My reviews</h1>

      <DataTable
        value={reviews}
        rowHover
        stripedRows
        emptyMessage={"You currently have no reviews."}
        removableSort
        onRowClick={(e) =>
          navigate(`/user-review/${e.data.id}`, {
            state: { review: e.data },
          })
        }
      >
        <Column
          field="name"
          header="Name"
          body={(row) => (row.type === "SONG" ? row.songName : row.albumName)}
          sortable
        />
        <Column
          header="Type"
          body={(value) => (
            <Tag
              value={value.type === "SONG" ? "Song" : "Album"}
              severity={value.type === "SONG" ? "success" : "info"}
            />
          )}
        />
        <Column
          field="grade"
          header="Rating"
          body={(value) => (
            <Rating value={value.grade} cancel={false} readOnly />
          )}
          sortable
        />
        <Column field="description" header="Description" />
        <Column
          field="creationDate"
          header="Creation Date"
          body={(row) => new Date(row.creationDate).toLocaleDateString("hr-HR")}
          sortable
        />
      </DataTable>
    </div>
  );
}

// mrp-vue/src/features/profile/Profile.page.vue
<template>
  <div class="flex flex-col items-center gap-15">
    <UserInfo />

    <div class="flex flex-col w-full gap-4">
      <p class="flex justify-start text-4xl font-bold">My reviews</p>

      <DataTable
        v-if="myReviews"
        :loading="isLoadingReviews"
        :value="myReviews"
        removableSort
        selectionMode="single"
        class="cursor-pointer"
        @row-click="(e) => openReviewDialog(e.data)"
      >
        <Column field="name" header="Name" :sortable="true">
          <template #body="{ data }: { data: ReviewResponse }">
            <div>
              {{
                data.type === ReviewType.SONG ? data.songName : data.albumName
              }}
            </div>
          </template>
        </Column>

        <Column field="type" header="Type" :sortable="true">
          <template #body="{ data }: { data: ReviewResponse }">
            <Tag
              :value="data.type === ReviewType.SONG ? 'Song' : 'Album'"
              :severity="data.type === ReviewType.ALBUM ? 'info' : 'success'"
            />
          </template>
        </Column>

        <Column field="rating" header="Rating" :sortable="true">
          <template #body="{ data }: { data: ReviewResponse }">
            <Rating :modelValue="data.grade" readonly />
          </template>
        </Column>

        <Column field="description" header="Description" />
        <Column field="creationDate" header="Creation date" :sortable="true">
          <template #body="{ data }: { data: ReviewResponse }">
            <div>
              {{ new Date(data.creationDate).toLocaleDateString("hr-HR") }}
            </div>
          </template>
        </Column>
      </DataTable>

      <p v-else>Error loading reviews</p>
    </div>

    <ReviewDialog
      v-model:visible="isReviewDialogVisible"
      :review-id="selectedReview?.id"
      :review-type="selectedReview?.type"
      @refetch="refetchMyReviews"
    />

    <div class="flex flex-col w-full gap-4">
      <div class="flex justify-between items-center">
        <p class="flex justify-start text-4xl font-bold">My playlists</p>
        <p>{{ myPlaylists?.totalElements }} total</p>
      </div>

      <DataTable
        :loading="isLoadingPlaylists"
        :value="myPlaylists?.content"
        removableSort
        selectionMode="single"
        @row-click="
          (e) =>
            router.push({ name: 'playlist-details', params: { id: e.data.id } })
        "
        class="cursor-pointer"
      >
        <Column field="name" header="Name" :sortable="true" />
        <Column field="isPrivate" header="Visibility" :sortable="true">
          <template #body="{ data }: { data: PlaylistResponseDto }">
            <Tag
              :value="data.isPrivate ? 'Private' : 'Public'"
              :severity="data.isPrivate ? 'danger' : 'success'"
            />
          </template>
        </Column>
        <Column field="ownerUsername" header="Owner" :sortable="true" />
        <Column field="songs" header="Songs" :sortable="true">
          <template #body="{ data }: { data: PlaylistResponseDto }">
            {{ data.songs.length }}
          </template>
        </Column>
        <Column field="collaborators" header="Collaborators" :sortable="true">
          <template #body="{ data }: { data: PlaylistResponseDto }">
            {{ data.collaborators.length }}
          </template>
        </Column>
        <Column field="description" header="Description">
          <template #body="{ data }: { data: PlaylistResponseDto }">
            <div>{{ data.description ?? "-" }}</div>
          </template>
        </Column>
      </DataTable>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import UserInfo from "./UserInfo.vue";
import { useRouter } from "vue-router";
import { useGetMyReviews, useGetMyPlaylists } from "@/features/profile/hooks";
import {
  type ReviewResponse,
  ReviewType,
  type PlaylistResponseDto,
} from "@/shared";
import { Tag, Rating } from "primevue";
import ReviewDialog from "@/features/review/ReviewDialog.vue";

const router = useRouter();
const {
  isLoading: isLoadingReviews,
  data: myReviews,
  refetch: refetchMyReviews,
} = useGetMyReviews();
const { isLoading: isLoadingPlaylists, data: myPlaylists } =
  useGetMyPlaylists();

const isReviewDialogVisible = ref(false);
const selectedReview = ref<ReviewResponse | null>(null);

const openReviewDialog = (review: ReviewResponse) => {
  selectedReview.value = review;
  isReviewDialogVisible.value = true;
};
</script>
