// mrp-react/src/features/user/UserInfo.tsx
import { Card } from "primereact/card";
import { Button } from "primereact/button";
import { UserInfoType } from "@shared/utils";

interface Props {
  user: UserInfoType | null;
  logout?: () => void;
}

export function UserInfo({ user, logout }: Props) {
  if (user) {
    return (
      <Card
        className="shadow-md rounded-lg"
        style={{ maxWidth: "400px", margin: "2rem auto" }}
      >
        <div className="flex flex-col gap-3">
          <div className="flex items-center gap-2">
            <span className="font-bold w-32">Username:</span>
            <span>{user.username}</span>
          </div>

          <div className="flex items-center gap-2">
            <span className="font-bold w-32">Email:</span>
            <span>{user.email}</span>
          </div>

          {logout && (
            <div className="flex justify-end">
              <Button
                label="Log out"
                icon="pi pi-sign-out"
                className="p-button-danger"
                onClick={logout}
              />
            </div>
          )}
        </div>
      </Card>
    );
  }
}

// mrp-vue/src/features/profile/UserInfo.vue
<template>
  <Card class="max-w-[400px] mt-10">
    <template #content>
      <div class="flex flex-col gap-3">
        <div class="flex items-center gap-2">
          <span class="font-bold w-8rem">Username:</span>
          <span>{user.username}</span>
        </div>

        <div class="flex items-center gap-2">
          <span class="font-bold w-8rem">Email:</span>
          <span>{user.email}</span>
        </div>

        <div class="flex justify-end">
          <Button icon="pi pi-sign-out" label="Log out" />
        </div>
      </div>
    </template>
  </Card>
</template>

<script setup lang="ts">
import { Card, Button } from "primevue";
</script>
