// mrp-react/src/features/review/CommentSection.tsx
import { useState } from "react";
import { Button } from "primereact/button";
import { InputTextarea } from "primereact/inputtextarea";
import { Message } from "primereact/message";
import { ProgressSpinner } from "primereact/progressspinner";
import { confirmDialog } from "primereact/confirmdialog";

import { UserRoleEnum } from "@shared/utils";
import { useGetComments } from "../../shared/hooks/useGetComments.ts";
import { useCurrentUser } from "../../shared/hooks/useCurrentUser.ts";
import { useNavigate } from "react-router-dom";
import { submitComment } from "./hooks/submitComment.ts";
import { updateComment } from "./hooks/updateComment.ts";
import { deleteComment } from "./hooks/deleteComment.ts";
import { toast } from "../../shared/components/ToastContext.tsx";

type Props = {
  reviewId: number;
  reviewType: "SONG" | "ALBUM";
};

export function CommentSection({ reviewId, reviewType }: Props) {
  const { user } = useCurrentUser();
  const navigate = useNavigate();
  const { comments, loading, error, refresh } = useGetComments(reviewId, reviewType);

  const [newContent, setNewContent] = useState("");
  const [posting, setPosting] = useState(false);

  const [editingId, setEditingId] = useState<number | null>(null);
  const [editContent, setEditContent] = useState("");
  const [saving, setSaving] = useState(false);

  const handlePost = async () => {
    const trimmed = newContent.trim();
    if (!trimmed) return;
    setPosting(true);
    try {
      await submitComment(reviewId, reviewType, trimmed);
      setNewContent("");
      await refresh();
    } catch {
      toast.error("Failed to post comment.");
    } finally {
      setPosting(false);
    }
  };

  const handleEditStart = (id: number, content: string) => {
    setEditingId(id);
    setEditContent(content);
  };

  const handleEditSave = async (commentId: number) => {
    const trimmed = editContent.trim();
    if (!trimmed) return;
    setSaving(true);
    try {
      await updateComment(commentId, reviewType, trimmed);
      setEditingId(null);
      await refresh();
    } catch {
      toast.error("Failed to update comment.");
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = (commentId: number) => {
    confirmDialog({
      header: "Delete Comment",
      message: "Delete this comment permanently?",
      icon: "pi pi-exclamation-triangle",
      acceptLabel: "Delete",
      rejectLabel: "Cancel",
      acceptClassName: "p-button-danger",
      accept: async () => {
        try {
          await deleteComment(commentId, reviewType);
          await refresh();
        } catch {
          toast.error("Failed to delete comment.");
        }
      },
    });
  };

  return (
    <div className="px-4 pb-4">
      <div className="text-[1rem] font-semibold mb-3">
        Comments {comments.length > 0 && `(${comments.length})`}
      </div>

      {loading && (
        <div className="flex justify-center py-4">
          <ProgressSpinner style={{ width: 32, height: 32 }} />
        </div>
      )}

      {!loading && error && (
        <Message severity="error" text={error} className="w-full mb-3" />
      )}

      {!loading && !error && comments.length === 0 && (
        <div className="text-[#6b7280] text-[0.9rem] mb-3">No comments yet.</div>
      )}

      {!loading && comments.map((comment) => {
        const date = new Date(comment.creationDate).toLocaleDateString("hr-HR", {
          timeZone: "UTC",
        });
        const canEdit = !!user && user.username === comment.username;
        const canDelete =
          !!user &&
          (user.username === comment.username || user.role === UserRoleEnum.ADMIN);
        const isEditing = editingId === comment.id;

        return (
          <div
            key={comment.id}
            className="border border-[#e5e7eb] rounded-[8px] p-3 mb-2"
          >
            <div className="flex items-center justify-between mb-1">
              <span className="text-[0.88rem] text-[#6b7280]">
                <span
                  className="inline-flex items-center gap-[4px] cursor-pointer select-none hover:underline"
                  onClick={() =>
                    user?.id === comment.userId
                      ? navigate("/profile")
                      : navigate(`/user/${comment.userId}`)
                  }
                >
                  <i className="pi pi-user" />
                  {comment.username}
                </span>
                <span className="mx-1 opacity-60">•</span>
                {date}
                {comment.updatedDate && (
                  <span className="ml-1 opacity-50 text-[0.82rem]">(edited)</span>
                )}
              </span>
              <div className="flex gap-2">
                {canEdit && !isEditing && (
                  <Button
                    icon="pi pi-pencil"
                    size="small"
                    text
                    severity="info"
                    onClick={() => handleEditStart(comment.id, comment.content)}
                    tooltip="Edit"
                    tooltipOptions={{ position: "top" }}
                  />
                )}
                {canDelete && !isEditing && (
                  <Button
                    icon="pi pi-trash"
                    size="small"
                    text
                    severity="danger"
                    onClick={() => handleDelete(comment.id)}
                    tooltip="Delete"
                    tooltipOptions={{ position: "top" }}
                  />
                )}
              </div>
            </div>

            {isEditing ? (
              <div className="flex flex-col gap-2 mt-1">
                <InputTextarea
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  rows={2}
                  autoResize
                  className="w-full"
                />
                <div className="flex gap-2">
                  <Button
                    label="Save"
                    icon={saving ? "pi pi-spin pi-spinner" : "pi pi-check"}
                    size="small"
                    severity="success"
                    disabled={saving || !editContent.trim()}
                    onClick={() => handleEditSave(comment.id)}
                  />
                  <Button
                    label="Cancel"
                    size="small"
                    severity="secondary"
                    text
                    onClick={() => setEditingId(null)}
                  />
                </div>
              </div>
            ) : (
              <p className="m-0 text-[0.95rem] text-[#374151] leading-[1.6] whitespace-pre-wrap">
                {comment.content}
              </p>
            )}
          </div>
        );
      })}

      {user && (
        <div className="flex flex-col gap-2 mt-3">
          <InputTextarea
            value={newContent}
            onChange={(e) => setNewContent(e.target.value)}
            placeholder="Write a comment..."
            rows={2}
            autoResize
            className="w-full"
          />
          <div className="flex justify-end">
            <Button
              label="Post"
              icon={posting ? "pi pi-spin pi-spinner" : "pi pi-send"}
              size="small"
              disabled={posting || !newContent.trim()}
              onClick={handlePost}
            />
          </div>
        </div>
      )}

    </div>
  );
}

// mrp-vue/src/features/review/CommentSection.vue
<template>
  <div class="flex flex-col gap-4 mt-4">
    <div class="flex items-center gap-2">
      <h3 class="text-lg font-semibold m-0">Comments</h3>
      <Badge
        v-if="!isLoading && comments.length > 0"
        :value="comments.length"
        severity="secondary"
      />
    </div>

    <div v-if="isLoading" class="flex justify-center p-4">
      <ProgressSpinner style="width: 32px; height: 32px" />
    </div>

    <div v-else-if="error" class="text-red-400 text-sm">
      {{ error.message }}
    </div>

    <div v-else-if="comments.length === 0" class="text-gray-400 text-sm">
      No comments yet.
    </div>

    <div v-else class="flex flex-col gap-3">
      <div
        v-for="comment in comments"
        :key="comment.id"
        class="border border-[#333] rounded-lg p-3 flex flex-col gap-2"
      >
        <div class="flex items-center justify-between gap-2 flex-wrap">
          <div class="flex items-center gap-2 text-sm">
            <span
              class="font-semibold cursor-pointer hover:text-primary transition-colors"
              @click="goToUser(comment)"
            >
              {{ comment.username }}
            </span>
            <span class="text-gray-500">
              {{ formatDate(comment.creationDate) }}
            </span>
            <span v-if="comment.updatedDate" class="text-gray-500 text-xs italic">
              (edited)
            </span>
          </div>
          <div class="flex items-center gap-1">
            <Button
              v-if="canEditComment(comment)"
              icon="pi pi-pencil"
              text
              rounded
              severity="info"
              size="small"
              @click="startEdit(comment)"
            />
            <Button
              v-if="canDeleteComment(comment)"
              icon="pi pi-trash"
              text
              rounded
              severity="danger"
              size="small"
              @click="confirmDelete(comment.id)"
            />
          </div>
        </div>

        <div v-if="editingId !== comment.id">
          <p class="text-sm whitespace-pre-wrap m-0">{{ comment.content }}</p>
        </div>
        <div v-else class="flex flex-col gap-2">
          <Textarea
            v-model="editContent"
            rows="3"
            class="w-full text-sm"
            auto-resize
          />
          <div class="flex gap-2">
            <Button
              label="Save"
              size="small"
              :loading="saving"
              :disabled="!editContent.trim() || saving"
              @click="saveEdit(comment.id)"
            />
            <Button
              label="Cancel"
              size="small"
              severity="secondary"
              outlined
              @click="cancelEdit"
            />
          </div>
        </div>
      </div>
    </div>

    <div v-if="isAuthenticated" class="flex flex-col gap-2 mt-2">
      <Textarea
        v-model="newContent"
        rows="3"
        placeholder="Write a comment..."
        class="w-full text-sm"
        auto-resize
      />
      <div class="flex justify-end">
        <Button
          label="Post"
          icon="pi pi-send"
          size="small"
          :loading="posting"
          :disabled="!newContent.trim() || posting"
          @click="postComment"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Role } from "@/features/login-register";
import { useAuthStore, type CommentResponse } from "@/shared";
import { storeToRefs } from "pinia";
import { Badge, Button, ProgressSpinner, Textarea } from "primevue";
import { useConfirm } from "primevue/useconfirm";
import { useToast } from "primevue/usetoast";
import { computed, ref, toRef } from "vue";
import { useCommentMutations } from "./hooks/useCommentMutations";
import { useGetComments } from "./hooks/useGetComments";
import router from "@/router/routes";

const props = defineProps<{
  reviewId: number;
  reviewType: "SONG" | "ALBUM";
}>();

const authStore = useAuthStore();
const { user, isAuthenticated } = storeToRefs(authStore);
const confirm = useConfirm();
const toast = useToast();

const { submitComment, updateComment, deleteComment } = useCommentMutations();

const { data, isLoading, error, refetch } = useGetComments(
  toRef(props, "reviewId"),
  toRef(props, "reviewType"),
);

const comments = computed<CommentResponse[]>(() => data.value?.content ?? []);

const newContent = ref("");
const posting = ref(false);

const editingId = ref<number | null>(null);
const editContent = ref("");
const saving = ref(false);

const formatDate = (dateStr: string) =>
  new Date(dateStr).toLocaleDateString("hr-HR", { timeZone: "UTC" });

const canEditComment = (comment: CommentResponse) =>
  !!user.value && user.value.username === comment.username;

const canDeleteComment = (comment: CommentResponse) =>
  !!user.value &&
  (user.value.username === comment.username || user.value.role === Role.ADMIN);

const goToUser = (comment: CommentResponse) => {
  if (user.value?.username === comment.username) {
    router.push("/profile");
  } else {
    router.push(`/user/${comment.userId}`);
  }
};

const postComment = async () => {
  if (!newContent.value.trim()) return;
  posting.value = true;
  try {
    await submitComment(props.reviewId, props.reviewType, newContent.value);
    newContent.value = "";
    await refetch();
  } catch (e) {
    toast.add({ severity: "error", summary: "Error", detail: "Failed to post comment.", life: 3000 });
  } finally {
    posting.value = false;
  }
};

const startEdit = (comment: CommentResponse) => {
  editingId.value = comment.id;
  editContent.value = comment.content;
};

const cancelEdit = () => {
  editingId.value = null;
  editContent.value = "";
};

const saveEdit = async (commentId: number) => {
  if (!editContent.value.trim()) return;
  saving.value = true;
  try {
    await updateComment(commentId, props.reviewType, editContent.value);
    editingId.value = null;
    editContent.value = "";
    await refetch();
  } catch (e) {
    toast.add({ severity: "error", summary: "Error", detail: "Failed to update comment.", life: 3000 });
  } finally {
    saving.value = false;
  }
};

const confirmDelete = (commentId: number) => {
  confirm.require({
    message: "Are you sure you want to delete this comment?",
    header: "Delete Comment",
    icon: "pi pi-exclamation-triangle",
    rejectProps: { label: "Cancel", severity: "secondary", outlined: true },
    acceptProps: { label: "Delete", severity: "danger" },
    accept: async () => {
      try {
        await deleteComment(commentId, props.reviewType);
        await refetch();
      } catch (e) {
        toast.add({ severity: "error", summary: "Error", detail: "Failed to delete comment.", life: 3000 });
      }
    },
  });
};
</script>
