// mrp-react/src/features/review/ReviewDialog.tsx
import { useState } from "react";
import { Dialog } from "primereact/dialog";
import { Card } from "primereact/card";
import { Image } from "primereact/image";
import { Rating } from "primereact/rating";
import { Tag } from "primereact/tag";
import { Divider } from "primereact/divider";
import { Button } from "primereact/button";
import { Message } from "primereact/message";
import { ProgressSpinner } from "primereact/progressspinner";

import {
  AlbumReviewFormData,
  AlbumType,
  SongReviewFormData,
  SongType,
  UserRoleEnum,
} from "@shared/utils";
import { useGetReview } from "../../shared/hooks/useGetReview.ts";
import { useGetImage } from "../../shared/hooks/useGetImage.ts";
import { useGetAlbum } from "../../shared/hooks/useGetAlbum.ts";
import { Chip } from "primereact/chip";
import { useGetSongFull } from "../../shared/hooks/useGetSongFull.ts";
import { CreateSongReview } from "../songs/CreateSongReview.tsx";
import { toast } from "../../shared/components/ToastContext.tsx";
import { CreateAlbumReview } from "../albums/CreateAlbumReview.tsx";
import { updateSongReview } from "../songs/hooks/updateAlbumReview.ts";
import { updateAlbumReview } from "../albums/hooks/updateAlbumReview.ts";
import { useCurrentUser } from "../../shared/hooks/useCurrentUser.ts";
import { ConfirmDialog, confirmDialog } from "primereact/confirmdialog";
import { deleteAlbumReview, deleteSongReview } from "./utils/helpers.tsx";
import { useNavigate } from "react-router-dom";
const VITE_BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

type Props = {
  visible: boolean;
  onHide: () => void;
  reviewId: number | undefined;
  reviewType?: "SONG" | "ALBUM";
  refetch: () => Promise<void>;
};

export default function ReviewDialog({
  visible,
  onHide,
  reviewId,
  reviewType,
  refetch,
}: Props) {
  const [visibleUpdateReview, setVisibleUpdateReview] =
    useState<boolean>(false);
  const [deleting, setDeleting] = useState<boolean>(false);

  const { user } = useCurrentUser();
  const navigate = useNavigate();

  const { review, loading, error } = useGetReview(reviewId, reviewType);
  const {
    loading: loadingReviewImg,
    exists: reviewImgExists,
    image: reviewImg,
  } = useGetImage(
    review?.image ? `${VITE_BACKEND_URL}${review?.image}` : undefined,
  );

  const songId = review?.type === "SONG" ? review.songId : undefined;
  const albumId = review?.type === "ALBUM" ? review.albumId : undefined;

  const {
    song,
    songAudio,
    songAudioExists,
    loading: loadingSong,
    loadingSongAudio,
    error: songError,
  } = useGetSongFull(songId ?? undefined);

  const {
    album,
    loading: loadingAlbum,
    error: albumError,
  } = useGetAlbum(albumId ?? undefined);

  const entity = (review?.type === "SONG" ? song : album) as
    | SongType
    | AlbumType
    | undefined;

  const createdAt = review
    ? new Date(review.creationDate).toLocaleDateString("hr-HR", {
        timeZone: "UTC",
      })
    : "";

  const canEdit = !!user && !!review && user.username === review.username;

  const canDelete =
    !!user &&
    !!review &&
    (user.username === review.username || user?.role === UserRoleEnum.ADMIN);

  const handleSubmit = async (
    formData: SongReviewFormData | AlbumReviewFormData,
  ) => {
    try {
      if (review?.type === "SONG") {
        await updateSongReview(reviewId!, formData as SongReviewFormData);
      } else if (review?.type === "ALBUM") {
        await updateAlbumReview(reviewId!, formData as AlbumReviewFormData);
      }
      onHide();
      toast.success(`Successfully updated review!`);
      refetch?.();
    } catch {
      toast.error("Something went wrong");
    }
  };

  const handleDelete = () => {
    if (!review || !reviewId) return;

    confirmDialog({
      header: "Confirm Delete",
      message: "Delete this review permanently?",
      icon: "pi pi-exclamation-triangle",
      acceptLabel: "Delete",
      rejectLabel: "Cancel",
      acceptClassName: "p-button-danger",
      accept: async () => {
        try {
          setDeleting(true);
          if (review.type === "SONG") {
            await deleteSongReview(reviewId);
          } else {
            await deleteAlbumReview(reviewId);
          }
          toast.success("Review deleted.");
          onHide();
          await refetch?.();
        } catch {
          toast.error("Failed to delete review.");
        } finally {
          setDeleting(false);
        }
      },
    });
  };

  const header = review && !loading && (
    <div className="flex items-center justify-between gap-3 w-full">
      <div className="ml-[5px]">
        <span className="text-[1.2rem] font-bold">
          {review?.type === "SONG"
            ? (review?.songName ?? "Song")
            : (review?.albumName ?? "Album")}
        </span>
      </div>
      <div className="flex items-center gap-5 mr-5">
        {canEdit && (
          <Button
            label="Edit"
            icon="pi pi-pencil"
            onClick={() => setVisibleUpdateReview(true)}
            severity="info"
            outlined
            size="small"
          />
        )}
        {canDelete && (
          <Button
            label="Delete"
            icon={deleting ? "pi pi-spin pi-spinner" : "pi pi-trash"}
            severity="danger"
            outlined
            size="small"
            onClick={handleDelete}
            disabled={deleting}
          />
        )}
        <Tag
          value={review?.type === "SONG" ? "Song Review" : "Album Review"}
          severity={review?.type === "SONG" ? "success" : "info"}
          rounded
        />
      </div>
    </div>
  );

  return (
    <Dialog
      visible={visible}
      onHide={onHide}
      header={header}
      className="rdialog"
      modal
      draggable={false}
      resizable={false}
      breakpoints={{ "1400px": "70vw", "960px": "85vw", "640px": "95vw" }}
      style={{ width: "60vw", maxWidth: 980 }}
    >
      {!reviewId && (
        <div className="min-h-[30vh] flex flex-col items-center justify-center gap-[10px]">
          <Message severity="error" text="Invalid review id." />
        </div>
      )}

      {reviewId && loading && (
        <div className="min-h-[30vh] flex flex-col items-center justify-center gap-[10px]">
          <ProgressSpinner />
          <div className="text-[#6b7280]">Loading…</div>
        </div>
      )}

      {reviewId && !loading && (error || !review) && (
        <div className="min-h-[30vh] flex flex-col items-center justify-center gap-[10px]">
          <Message severity="error" text={error ?? "Review not found."} />
        </div>
      )}

      {reviewId && !loading && review && (
        <Card className="rdialog__card shadow-md">
          <div className="rdialog__hero" style={{ display: "grid", gridTemplateColumns: "320px 1fr", gap: 20, padding: "16px 16px 0 16px" }}>
            <div className="w-full h-[220px] bg-[#f5f5f5] overflow-hidden rounded-[10px]">
              <Image
                src={
                  !loadingReviewImg && reviewImgExists
                    ? (reviewImg ?? undefined)
                    : undefined
                }
                alt={
                  review.type === "SONG"
                    ? (review.songName ?? "Song")
                    : (review.albumName ?? "Album")
                }
                imageClassName="w-full h-full object-cover"
              />
            </div>

            <div className="flex flex-col gap-[10px]">
              <div className="flex items-center gap-2 text-[#6b7280] text-[0.95rem]">
                <span
                  className="inline-flex items-center gap-[6px] cursor-pointer select-none"
                  onClick={() => {
                    if (user?.id === review?.userId) {
                      navigate(`/profile`);
                    } else {
                      navigate(`/user/${review?.userId}`);
                    }
                  }}
                >
                  <i className="pi pi-user" /> {review.username}
                </span>
                <span className="opacity-70">•</span>
                <span className="inline-flex items-center gap-[6px]">
                  <i className="pi pi-calendar" /> {createdAt}
                </span>
              </div>

              <div className="mt-1">
                <Rating value={review.grade} cancel={false} readOnly />
              </div>

              <p className="m-0 text-[#374151] leading-[1.65] text-[0.98rem]">{review.description}</p>
            </div>
          </div>

          <Divider />

          <div className="px-4 pb-4">
            <div className="rdialog__entity" style={{ display: "grid", gridTemplateColumns: "220px 1fr", gap: 16, alignItems: "start" }}>
              <div className="flex flex-col gap-[10px]">
                {review.type === "SONG" && entity && (
                  <>
                    <div className="font-bold text-[1.1rem]">
                      {(entity as SongType).name}
                    </div>
                    {(entity as SongType).year ? (
                      <div className="text-[#6b7280] text-[0.95rem]">
                        Released {(entity as SongType).year}
                      </div>
                    ) : null}

                    <div className="flex gap-2 flex-wrap my-[6px]">
                      {(entity as SongType).genres?.map((g) => (
                        <Chip
                          key={g.id}
                          label={g.name}
                          className="text-[0.85rem]"
                        />
                      ))}
                    </div>

                    <div className="mt-1">
                      {(entity as SongType).link && (
                        <Button
                          label="Open Song Link"
                          icon="pi pi-external-link"
                          onClick={() =>
                            window.open((entity as SongType).link!, "_blank")
                          }
                        />
                      )}
                    </div>
                  </>
                )}

                {review.type === "ALBUM" && entity && (
                  <>
                    <div className="font-bold text-[1.1rem]">
                      {(entity as AlbumType).name}
                    </div>
                    {(entity as AlbumType).year ? (
                      <div className="text-[#6b7280] text-[0.95rem]">
                        Released {(entity as AlbumType).year}
                      </div>
                    ) : null}

                    <div className="mt-1">
                      {(entity as AlbumType).link && (
                        <Button
                          label="Open Album Link"
                          icon="pi pi-external-link"
                          onClick={() =>
                            window.open((entity as AlbumType).link!, "_blank")
                          }
                        />
                      )}
                    </div>
                  </>
                )}

                {(loadingSong || loadingAlbum) && (
                  <div className="text-[#6b7280] text-[0.95rem]">
                    <i className="pi pi-spin pi-spinner" /> Loading details…
                  </div>
                )}
                {(songError || albumError) && (
                  <div className="text-[#6b7280] text-[0.95rem]">
                    <i className="pi pi-exclamation-triangle" /> Couldn't load
                    details.
                  </div>
                )}
              </div>
              {review.type === "SONG" && (
                <div className="my-auto">
                  {loadingSongAudio ? (
                    <i className="pi pi-spin pi-spinner" />
                  ) : songAudioExists && songAudio ? (
                    <audio controls src={songAudio} className="w-full" />
                  ) : (
                    <div className="w-full h-full">
                      No audio file available.
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </Card>
      )}

      {visibleUpdateReview && review && review.songId && !loading && (
        <CreateSongReview
          visible={visibleUpdateReview}
          name={review?.songName ?? ""}
          songId={review.songId}
          onHide={() => setVisibleUpdateReview(false)}
          onSubmit={handleSubmit}
          existingFormData={{
            songId: review.songId,
            grade: review?.grade,
            description: review?.description,
          }}
        />
      )}
      {visibleUpdateReview && review && review.albumId && !loading && (
        <CreateAlbumReview
          visible={visibleUpdateReview}
          name={review?.albumName ?? ""}
          albumId={review.albumId}
          onHide={() => setVisibleUpdateReview(false)}
          onSubmit={handleSubmit}
          existingFormData={{
            albumId: review.albumId,
            grade: review?.grade,
            description: review?.description,
          }}
        />
      )}
      <ConfirmDialog />
    </Dialog>
  );
}

// mrp-vue/src/features/review/ReviewDialog.vue
<template>
  <Dialog
    :visible="visible"
    @update:visible="$emit('update:visible', $event)"
    modal
    :draggable="false"
    :resizable="false"
    class="w-[95vw] md:w-[85vw] lg:w-[70vw] xl:w-[60vw] max-w-[980px] p-dark"
  >
    <template #header>
      <div class="flex justify-between items-center w-full pr-2">
        <span class="text-xl font-bold">{{ headerTitle }}</span>
        <div class="flex items-center gap-2">
          <Button
            v-if="canEdit"
            label="Edit"
            icon="pi pi-pencil"
            severity="info"
            outlined
            size="small"
            @click="onEdit"
          />
          <Button
            v-if="canDelete"
            label="Delete"
            icon="pi pi-trash"
            severity="danger"
            outlined
            size="small"
            @click="onDelete"
          />
          <Tag
            :value="review?.type === 'SONG' ? 'Song Review' : 'Album Review'"
            :severity="review?.type === 'SONG' ? 'success' : 'info'"
            rounded
          />
        </div>
      </div>
    </template>
    <div
      v-if="isLoading"
      class="flex flex-col items-center justify-center p-8 gap-4"
    >
      <ProgressSpinner />
      <span class="text-gray-500">Loading...</span>
    </div>

    <div v-else-if="error || !review" class="p-8 text-center text-red-500">
      <i class="pi pi-exclamation-triangle text-4xl mb-4" />
      <p>{{ error?.message || "Review not found." }}</p>
    </div>

    <Card v-else class="shadow-white rounded-[15px]">
      <template #content>
        <div class="flex flex-col gap-4">
          <div class="flex gap-8">
            <div
              class="rounded-lg overflow-hidden w-[180px] h-[180px] shrink-0 bg-[#2a2a2a] flex items-center justify-center"
            >
              <Image
                v-if="displayImageUrl"
                :src="displayImageUrl"
                alt="Review Image"
                image-class="object-cover w-full h-full"
                class="w-full h-full"
              />
              <i
                v-if="!displayImageUrl && isImageLoading"
                class="pi pi-spin pi-spinner text-4xl"
              />
              <i
                v-else-if="!displayImageUrl"
                class="pi pi-image text-4xl text-gray-400"
              />
            </div>

            <div class="flex flex-col gap-4">
              <div class="flex flex-col gap-1">
                <h2 class="text-3xl font-bold m-0">{{ headerTitle }}</h2>
                <div class="flex items-center gap-2 text-gray-400 text-sm">
                  <span
                    class="flex items-center gap-1 cursor-pointer hover:text-primary transition-colors"
                    @click="goToUser"
                  >
                    <i class="pi pi-user" /> {{ review.username }}
                  </span>
                  <span>•</span>
                  <span class="flex items-center gap-1">
                    <i class="pi pi-calendar" /> {{ formattedDate }}
                  </span>
                </div>
              </div>

              <div class="flex items-center gap-2 mt-2">
                <Rating :model-value="review.grade" readonly :cancel="false" />
              </div>

              <div>
                <h3 class="text-lg font-semibold mb-2">Review</h3>
                <p class="text-white! leading-relaxed whitespace-pre-wrap">
                  {{ review.description }}
                </p>
              </div>
            </div>
          </div>

          <div
            v-if="entity"
            class="bg-[#1a1a1a] p-4 rounded-lg flex flex-col gap-4"
          >
            <div>
              <h4 class="font-bold text-lg">{{ entity.name }}</h4>
              <p v-if="'year' in entity" class="text-sm text-gray-400">
                Released {{ entity.year }}
              </p>
            </div>

            <div
              v-if="review.type === 'SONG' && (entity as any).genres"
              class="flex flex-wrap gap-1"
            >
              <Chip
                v-for="genre in (entity as any).genres"
                :key="genre.id"
                :label="genre.name"
                class="text-xs"
              />
            </div>
            <div v-else>
              <p class="text-gray-400 h-2rem">No genres available.</p>
            </div>

            <Button
              v-if="'link' in entity && entity.link"
              :label="
                review.type === 'SONG' ? 'Open Song Link' : 'Open Album Link'
              "
              icon="pi pi-external-link"
              outlined
              @click="openExternalLink(entity.link)"
            />

            <div v-if="review.type === 'SONG'" class="mt-4">
              <div v-if="isSongLoading" class="flex justify-center p-4">
                <i class="pi pi-spin pi-spinner" />
              </div>
              <div v-else-if="songAudioUrl" class="w-full">
                <audio controls :src="songAudioUrl" class="w-full" />
              </div>
              <div
                v-else
                class="text-center p-4 bg-[#1a1a1a] rounded text-gray-400 text-sm"
              >
                No audio file available.
              </div>
            </div>
          </div>
        </div>
      </template>
    </Card>
  </Dialog>
  <EditReviewDialog
    v-if="isEditDialogVisible && review"
    v-model:visible="isEditDialogVisible"
    :review-id="reviewId!"
    :review-type="reviewType!"
    :name="headerTitle"
    :initial-values="{
      grade: review.grade,
      description: review.description,
      songId: review.songId,
      albumId: review.albumId,
    }"
    @success="onEditSuccess"
  />
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import {
  Dialog,
  Button,
  Tag,
  Card,
  Rating,
  Chip,
  ProgressSpinner,
  Image,
} from "primevue";
import { useAuthStore, useGetFile } from "@/shared";
import { useGetReview } from "@/features";
import { useGetSong } from "../songs/hooks/useGetSong";
import { useDeleteReview } from "@/features";
import EditReviewDialog from "./EditReviewDialog.vue";
import { Role } from "@/features";
import { storeToRefs } from "pinia";
import router from "@/router/routes";

const props = defineProps<{
  visible: boolean;
  reviewId: number | undefined;
  reviewType: "SONG" | "ALBUM" | undefined;
}>();

const emit = defineEmits<{
  (e: "update:visible", value: boolean): void;
  (e: "edit", reviewId: number): void;
  (e: "delete", reviewId: number): void;
  (e: "refetch"): void;
}>();

const authStore = useAuthStore();
const { user } = storeToRefs(authStore);

const { deleteReview } = useDeleteReview();

const isEditDialogVisible = ref(false);
const isDeleting = ref(false);

// Fetch Review
const {
  data: review,
  isLoading,
  error,
  refetch: refetchReview,
} = useGetReview(props.reviewId, props.reviewType);

// Fetch Entity (Song or Album)
const songId = computed(() =>
  review.value?.type === "SONG" ? review.value.songId : undefined,
);
// const albumId = computed(() => (review.value?.type === 'ALBUM' ? review.value.albumId : undefined));

const { data: song, isLoading: isSongLoading } = useGetSong(songId);
// const { data: album } = useGetAlbum(albumId.value); // Add this when album feature is ready

const entity = computed(() => {
  if (review.value?.type === "SONG") return song.value;
  // if (review.value?.type === 'ALBUM') return album.value;
  return null;
});

// Files
const imageUrl = computed(() => {
  if (review.value?.type === "SONG" && song.value?.imageUrl) {
    return song.value.imageUrl;
  }
  return review.value?.image;
});

// const audioUrl = computed(() => {
//   if (review.value?.type === "SONG" && review.value.songId) {
//     return `/api/song/audio-file/${review.value.songId}`;
//   }
//   return review.value?.image;
// });

const { fileUrl: displayImageUrl, isLoading: isImageLoading } =
  useGetFile(imageUrl);

const audioUrl = computed(() => song.value?.fileUrl);

const { fileUrl: songAudioUrl } = useGetFile(audioUrl);

const headerTitle = computed(() => {
  if (!review.value) return "Review";
  return review.value.type === "SONG"
    ? (review.value.songName ?? "Song Review")
    : (review.value.albumName ?? "Album Review");
});

const formattedDate = computed(() => {
  if (!review.value) return "";
  return new Date(review.value.creationDate).toLocaleDateString("hr-HR");
});

const canEdit = computed(() => {
  return (
    !!user.value &&
    !!review.value &&
    user.value.username === review.value.username
  );
});

const canDelete = computed(() => {
  return (
    !!user.value &&
    !!review.value &&
    (user.value.username === review.value.username ||
      user.value.role === Role.ADMIN)
  );
});

const onEdit = () => {
  isEditDialogVisible.value = true;
};

const onEditSuccess = () => {
  refetchReview();
  emit("refetch");
};

const onDelete = async () => {
  if (!props.reviewId || !props.reviewType) return;

  if (confirm("Are you sure you want to delete this review?")) {
    try {
      isDeleting.value = true;
      await deleteReview(props.reviewId, props.reviewType);
      emit("refetch");
      emit("update:visible", false);
    } catch (e) {
      console.error("Failed to delete review:", e);
    } finally {
      isDeleting.value = false;
    }
  }
};

const openExternalLink = (link: string) => {
  window.open(link, "_blank");
};

const goToUser = () => {
  if (!review.value) return;
  if (user.value?.username === review.value.username) {
    router.push("/profile");
  } else {
    router.push(`/user/${review.value.userId}`);
  }
  emit("update:visible", false);
};
</script>
