// mrp-react/src/shared/components/ReviewCard.tsx
import { useState } from "react";
import { Card } from "primereact/card";
import { Tag } from "primereact/tag";
import { Rating } from "primereact/rating";
import { Image } from "primereact/image";
import { ReviewResponse } from "@shared/utils";
import { useGetImage } from "../hooks/useGetImage";
import ReviewDialog from "../../features/review/ReviewDialog.tsx";
const VITE_BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

interface ReviewCardProps {
  review: ReviewResponse;
  refetch: () => Promise<void>;
}

export const ReviewCard = ({ review, refetch }: ReviewCardProps) => {
  const [visible, setVisible] = useState(false);

  const title =
    review.type === "SONG"
      ? (review.songName ?? "Song")
      : (review.albumName ?? "Album");

  const { loading, exists, image } = useGetImage(
    review.image
      ? review.image.startsWith("/api")
        ? review.image
        : `${VITE_BACKEND_URL}${review.image}`
      : undefined,
  );

  const header = (
    <div className="w-full h-[180px] bg-[#f5f5f5] overflow-hidden">
      {loading ? (
        <div className="w-full h-full flex items-center justify-center">
          <i className="pi pi-spin pi-spinner" />
        </div>
      ) : (
        <Image
          src={exists && image ? image : undefined}
          imageStyle={{ width: "100%", height: 180, objectFit: "cover" }}
        />
      )}
    </div>
  );

  const footer = (
    <div className="flex justify-between items-center mt-4">
      <span className="text-sm text-[#6b6b6b]">
        {new Date(review.creationDate).toLocaleDateString("hr-HR")}
      </span>
      <Tag
        value={review.username}
        severity="warning"
        style={{ fontWeight: 600, padding: "0.25rem 0.75rem" }}
      />
    </div>
  );

  return (
    <>
      <Card
        title={title}
        header={header}
        footer={footer}
        style={{
          width: 300,
          borderRadius: "0.5rem",
          boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
          margin: "1rem",
          overflow: "hidden",
          cursor: "pointer",
        }}
        onClick={() => setVisible(true)}
      >
        <div className="flex flex-wrap justify-between mb-2">
          <Rating value={review.grade} readOnly cancel={false} stars={5} />
          <Tag
            value={review.type === "SONG" ? "Song" : "Album"}
            severity={review.type === "SONG" ? "success" : "info"}
            style={{ fontWeight: 600, padding: "0.25rem 0.75rem" }}
          />
        </div>
        <p className="text-sm leading-relaxed">{review.description}</p>
      </Card>

      {visible && (
        <ReviewDialog
          visible={visible}
          onHide={() => setVisible(false)}
          reviewId={review.id}
          reviewType={review.type}
          refetch={refetch}
        />
      )}
    </>
  );
};

// mrp-vue/src/shared/components/ReviewCard.vue
<template>
  <Card
    class="w-[300px] rounded-lg! shadow-md! shadow-black m-4 overflow-hidden cursor-pointer"
    @click="onCardClick"
  >
    <template #header>
      <div
        class="w-full h-[180px] rounded-t-lg! object-cover bg-[#5f5f5f] flex justify-center items-center overflow-hidden"
      >
        <Image
          v-if="imageUrl"
          :src="imageUrl"
          alt="Review Image"
          image-class="object-cover w-full h-full"
          class="w-full h-full"
        />
        <i
          v-if="!imageUrl && isLoading"
          class="pi pi-spin pi-spinner text-4xl"
        />
        <i v-else-if="!imageUrl" class="pi pi-image text-4xl" />
      </div>
    </template>

    <template #title>
      <p class="m-0 p-0 text-xl font-bold truncate">{{ title }}</p>
    </template>

    <template #content>
      <div class="flex flex-col gap-4">
        <div class="flex flex-wrap justify-between items-center mb-2">
          <Rating
            :model-value="review.grade"
            readonly
            :cancel="false"
            :stars="5"
          />
          <Tag
            :value="review.type === 'SONG' ? 'Song' : 'Album'"
            :severity="review.type === 'SONG' ? 'success' : 'info'"
            class="font-semibold px-3 py-1"
          />
        </div>
        <p
          class="text-sm leading-relaxed m-0 h-[3rem] overflow-hidden text-ellipsis"
        >
          {{ review.description }}
        </p>
      </div>
    </template>

    <template #footer>
      <div class="flex justify-between items-center mt-4 pt-4">
        <span class="text-xs text-gray-400">
          {{ new Date(review.creationDate).toLocaleDateString("hr-HR") }}
        </span>
        <Tag
          :value="review.username"
          severity="warn"
          class="font-semibold px-3 py-1"
        />
      </div>
    </template>
  </Card>

  <ReviewDialog
    v-if="isDialogVisible"
    v-model:visible="isDialogVisible"
    :review-id="review.id"
    :review-type="review.type"
    @refetch="onRefetch"
  />
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { Card, Tag, Rating, Image } from "primevue";
import type { ReviewResponse } from "@/shared";
import { useGetFile } from "@/shared";
import { ReviewDialog } from "@/features";

const props = defineProps<{
  review: ReviewResponse;
}>();

const emit = defineEmits<{
  (e: "click", review: ReviewResponse): void;
  (e: "refetch"): void;
}>();

const isDialogVisible = ref(false);

const title = computed(() => {
  return props.review.type === "SONG"
    ? (props.review.songName ?? "Song")
    : (props.review.albumName ?? "Album");
});

const { fileUrl: imageUrl, isLoading } = useGetFile(props.review.image);

const onCardClick = () => {
  isDialogVisible.value = true;
  emit("click", props.review);
};

const onRefetch = () => {
  emit("refetch");
};
</script>
