// mrp-react/src/shared/components/PlaylistCard.tsx
import { Card } from "primereact/card";
import { Tag } from "primereact/tag";
import { Badge } from "primereact/badge";
import { Image } from "primereact/image";
import { useGetImage } from "../hooks/useGetImage";
import { PlaylistType } from "@shared/utils";
import { useNavigate } from "react-router-dom";
const VITE_BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

export default function PlaylistCard({ playlist }: { playlist: PlaylistType }) {
  const navigate = useNavigate();

  const isPublic = !playlist.isPrivate;

  const {
    loading: loadingImage,
    exists: imageExists,
    image: image,
  } = useGetImage(`${VITE_BACKEND_URL}${playlist.image}`);

  const songsCount = Array.isArray(playlist.songs) ? playlist.songs.length : 0;

  const collaboratorsCount = Array.isArray(playlist.collaborators)
    ? playlist.collaborators.length
    : 0;

  const header = (
    <div className="w-full h-[180px] bg-[#f5f5f5] overflow-hidden relative">
      {loadingImage ? (
        <div className="w-full h-full flex items-center justify-center">
          <i className="pi pi-spin pi-spinner" />
        </div>
      ) : (
        <Image
          src={imageExists && image ? image : undefined}
          alt={`${playlist.name} cover`}
          imageClassName="w-full h-full object-cover block"
          className="block w-full h-full"
        />
      )}
    </div>
  );

  return (
    <Card
      className="playlist-card select-none cursor-pointer"
      style={{ width: 320, display: "flex", flexDirection: "column" }}
      header={header}
      onClick={() => navigate(`/playlist/${playlist.id}`)}
    >
      <div className="flex flex-col p-5 gap-2">
        <div className="flex items-center justify-between min-h-[40px] mb-1">
          <h3 className="m-0 text-xl leading-tight line-clamp-2">{playlist.name}</h3>
          <Tag
            value={isPublic ? "Public" : "Private"}
            severity={isPublic ? "success" : "secondary"}
            rounded
          />
        </div>

        {playlist.description && (
          <p className="text-[#374151] leading-relaxed">{playlist.description}</p>
        )}

        <div className="flex items-center justify-between pt-[6px]">
          <Tag value={playlist.ownerUsername} severity="warning" />
          <div className="flex gap-3">
            <span className="inline-flex items-center gap-[6px]">
              <i className="pi pi-headphones" />
              <Badge value={songsCount} />
            </span>
            <span className="inline-flex items-center gap-[6px]">
              <i className="pi pi-users" />
              <Badge value={collaboratorsCount} />
            </span>
          </div>
        </div>
      </div>
    </Card>
  );
}

// mrp-vue/src/features/playlists/PlaylistCard.vue
<template>
  <Card
    class="w-[320px] h-[300px] rounded-lg! shadow-md! shadow-black cursor-pointer"
    @click="$emit('playlist-click', playlist)"
  >
    <template #header>
      <div
        class="w-full h-[180px] rounded-t-lg! object-cover bg-[#5f5f5f] flex justify-center items-center overflow-hidden"
      >
        <Image
          v-if="imageUrl"
          :src="imageUrl"
          image-class="object-cover w-full h-full"
          class="w-full h-full"
        />
        <ProgressSpinner v-else-if="isImageLoading" />
        <i v-else class="pi pi-list-music text-4xl" />
      </div>
    </template>

    <template #title>
      <div class="flex justify-between items-center">
        <p class="m-0 p-0 text-xl font-bold truncate">{{ playlist.name }}</p>
        <div class="flex gap-3 text-sm text-gray-400 shrink-0">
          <span class="flex items-center gap-1">
            <i class="pi pi-headphones" /> {{ playlist.songs?.length || 0 }}
          </span>
          <span class="flex items-center gap-1">
            <i :class="playlist.isPrivate ? 'pi pi-lock' : 'pi pi-lock-open'" />
          </span>
        </div>
      </div>
    </template>

    <template #subtitle>
      <span class="text-gray-400 text-xs">by {{ playlist.ownerUsername }}</span>
      <span v-if="playlist.description" class="block line-clamp-1 text-sm mt-1">
        {{ playlist.description }}
      </span>
      <span v-else class="block text-gray-500 italic text-sm mt-1">No description.</span>
    </template>
  </Card>
</template>

<script setup lang="ts">
import { Card, Image, ProgressSpinner } from "primevue";
import type { PlaylistResponseDto } from "@/shared";
import { useGetFile } from "@/shared";

const props = defineProps<{
  playlist: PlaylistResponseDto;
}>();

defineEmits<{
  (e: "playlist-click", playlist: PlaylistResponseDto): void;
}>();

const { fileUrl: imageUrl, isLoading: isImageLoading } = useGetFile(
  props.playlist.image,
);
</script>
