// mrp-vue/src/shared/components/Layout.vue
<script setup>
import TabMenu from "primevue/tabmenu";
import { MOBILE_TABS_MENU, TABS_MENU } from "@/shared/constants.ts";
import { useMediaQuery } from "@vueuse/core";
import { computed } from "vue";
import { useRoute } from "vue-router";
import router from "@/router/routes.ts";

const route = useRoute();
const isMobile = useMediaQuery("(max-width: 850px)");

const model = computed(() => (isMobile.value ? MOBILE_TABS_MENU : TABS_MENU));

const TAB_PATHS = [
  "/",
  "/all-reviews",
  "/songs",
  "/albums",
  "/artists",
  "/playlists",
  "/profile",
];

const activeIndex = computed(() => {
  const i = TAB_PATHS.findIndex((path) => path === route.path);
  return i >= 0 ? i : 0;
});

const changeTab = (e) => {
  const path = TAB_PATHS[e.index];
  if (path) router.push(path);
};
</script>

<template>
  <div>
    <TabMenu
      class="flex justify-center mb-[2rem]"
      :model="model"
      :active-index="activeIndex"
      @tabChange="changeTab"
    />
    <router-view />
  </div>
</template>

// mrp-react/src/pages/Layout.tsx
import { Outlet, useLocation, useNavigate } from "react-router-dom";
import { useMemo } from "react";
import { TabMenu, TabMenuTabChangeEvent } from "primereact/tabmenu";
import { MOBILE_TABS_MENU, TABS_MENU } from "@shared/utils";
import { useMatchMedia } from "primereact/hooks";

export default function Layout() {
  const navigate = useNavigate();
  const location = useLocation();
  const isMobile = useMatchMedia("(max-width: 760px)");

  const TAB_PATHS = useMemo(
    () => [
      "/",
      "/all-reviews",
      "/songs",
      "/albums",
      "/artists",
      "/playlists",
      `/profile`,
    ],
    [],
  );

  const model = isMobile ? MOBILE_TABS_MENU : TABS_MENU;

  const activeIndex = useMemo(() => {
    const i = TAB_PATHS.findIndex((playlist) => playlist === location.pathname);
    return i >= 0 ? i : 0;
  }, [location.pathname, TAB_PATHS]);

  const changeTab = (e: TabMenuTabChangeEvent) => {
    const path = TAB_PATHS[e.index];
    if (path) navigate(path);
  };

  return (
    <div className="flex flex-column">
      <TabMenu
        pt={{
          menu: { style: { justifyContent: isMobile ? "space-between" : "" } },
          icon: { style: { fontSize: isMobile ? "1.5rem" : "" } },
        }}
        model={model}
        className="mx-auto text-center w-full md:w-auto"
        activeIndex={activeIndex}
        onTabChange={changeTab}
      />
      <div className="m-5">
        <Outlet />
      </div>
    </div>
  );
}
