// mrp-vue/src/features/playlists/Playlists.page.vue
<template>
  <div class="flex flex-col gap-4 items-center">
    <Button
      label="Add New Playlist"
      icon="pi pi-plus"
      class="w-fit"
      @click="isDialogVisible = true"
    />

    <div v-if="isLoading" class="flex justify-center items-center h-64">
      <ProgressSpinner />
    </div>

    <div v-else-if="error" class="text-center text-red-500">
      <p>Error loading playlists: {{ error.message }}</p>
    </div>

    <div
      v-else-if="playlists && playlists.content.length > 0"
      class="flex flex-wrap gap-4 justify-center"
    >
      <PlaylistCard
        v-for="playlist in playlists.content"
        :key="playlist.id"
        :playlist="playlist"
        @playlist-click="onPlaylistClick"
      />
    </div>

    <div v-else class="text-center text-gray-500">
      <p>No playlists found.</p>
    </div>
  </div>

  <CreatePlaylistDialog v-model="isDialogVisible" @refetchPlaylists="refetchPlaylists" />
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { ProgressSpinner, Button } from "primevue";
import type { PlaylistResponseDto } from "@/shared";
import PlaylistCard from "./PlaylistCard.vue";
import CreatePlaylistDialog from "./CreatePlaylistDialog.vue";
import { useGetPublicPlaylists } from "./hooks/useGetAllPlaylists";

const {
  data: playlists,
  isLoading,
  error,
  refetch: refetchPlaylists,
} = useGetPublicPlaylists();

const router = useRouter();
const isDialogVisible = ref(false);

const onPlaylistClick = (playlist: PlaylistResponseDto) => {
  router.push(`/playlist/${playlist.id}`);
};
</script>

// mrp-react/src/features/playlists/Playlists.page.tsx
import { useState } from "react";
import { Button } from "primereact/button";
import { useGetPlaylists } from "./hooks/useGetPlaylists.ts";
import PlaylistCard from "../../shared/components/PlaylistCard.tsx";
import CreatePlaylistDialog from "./CreatePlaylistDialog.tsx";
import { ProgressSpinner } from "primereact/progressspinner";
import { Message } from "primereact/message";

export default function PlaylistsPage() {
  const { data: playlists, loading, error, refetch } = useGetPlaylists();
  const [visibleDialog, setVisibleDialog] = useState<boolean>(false);

  if (loading) {
    return (
      <div className="page-status">
        <ProgressSpinner />
        <div className="page-status__text">Loading…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="page-status">
        <Message severity="error" text={`Error: ${error}`} />
        <Button
          label="Retry"
          icon="pi pi-refresh"
          onClick={refetch}
          className="page-status__action"
        />
      </div>
    );
  }

  return (
    <>
      <div className="flex flex-column justify-content-center align-items-center gap-4">
        <Button
          label="Add New Playlist"
          className="w-15rem"
          icon="pi pi-plus"
          onClick={() => setVisibleDialog(true)}
        />

        <div className="flex flex-wrap gap-4 justify-content-center w-full">
          {(playlists ?? []).map((p) => (
            <PlaylistCard key={`playlist${p.id}`} p={p} />
          ))}
          {!loading && !error && playlists?.length === 0 && (
            <div className="text-empty">No public playlists found.</div>
          )}
        </div>
      </div>

      {visibleDialog && (
        <CreatePlaylistDialog
          visible={visibleDialog}
          setVisible={setVisibleDialog}
          onCreated={refetch}
        />
      )}
    </>
  );
}
