// mrp-react/src/features/albums/AlbumDetails.page.tsx
import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";

import { Card } from "primereact/card";
import { Image } from "primereact/image";
import { Button } from "primereact/button";
import { Divider } from "primereact/divider";
import { Message } from "primereact/message";
import { ProgressSpinner } from "primereact/progressspinner";
import {
  DataTable,
  DataTablePageEvent,
  DataTableStateEvent,
} from "primereact/datatable";
import { Column } from "primereact/column";
import { Rating } from "primereact/rating";
import { Tag } from "primereact/tag";

import ReviewDialog from "../../features/review/ReviewDialog.tsx";
import { useGetAlbum } from "../../shared/hooks/useGetAlbum.ts";
import { useGetImage } from "../../shared/hooks/useGetImage.ts";
import { useGetAlbumReviews } from "../../shared/hooks/useGetAlbumReviews.ts";
import {
  ArtistType,
  GenreType,
  ReviewResponse,
  SongType,
  UserRoleEnum,
} from "@shared/utils";
import { Chip } from "primereact/chip";
import { useCurrentUser } from "../../shared/hooks/useCurrentUser.ts";
import { ConfirmDialog, confirmDialog } from "primereact/confirmdialog";
import { toast } from "../../shared/components/ToastContext.tsx";
import CreateAlbumDialog from "./CreateAlbumDialog.tsx";
import { deleteAlbum } from "./utils/helpers.tsx";

const VITE_BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

export default function AlbumDetailsPage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const albumId = useMemo(() => (id ? Number(id) : undefined), [id]);
  const {
    album,
    loading: loadingAlbum,
    error: albumError,
    refetch: albumRefetch,
  } = useGetAlbum(albumId);
  const {
    loading: loadingCover,
    exists: coverExists,
    image: coverSrc,
    imageAsJsFile,
    refetch: refetchImage,
  } = useGetImage(
    albumId ? `${VITE_BACKEND_URL}/images/album/${albumId}` : undefined,
  );
  const {
    reviews,
    total,
    page,
    rows,
    loading: loadingReviews,
    error: reviewsError,
    sortField,
    sortOrder,
    onPage,
    onSort,
    refresh,
  } = useGetAlbumReviews(albumId);
  const { user } = useCurrentUser();

  const [dialogVisible, setDialogVisible] = useState(false);
  const [selectedReviewId, setSelectedReviewId] = useState<
    number | undefined
  >();

  const [editAlbumDialogVisible, setEditAlbumDialogVisible] =
    useState<boolean>(false);

  const [deleting, setDeleting] = useState<boolean>(false);

  const openDialog = (row: ReviewResponse) => {
    setSelectedReviewId(row.id);
    setDialogVisible(true);
  };
  const closeDialog = () => setDialogVisible(false);

  const handlePage = (e: DataTablePageEvent) => {
    onPage({ first: e.first, rows: e.rows, page: e.page });
  };

  const handleSort = (e: DataTableStateEvent) => {
    const normalized: 1 | -1 | undefined =
      e.sortOrder === 1 ? 1 : e.sortOrder === -1 ? -1 : undefined;

    onSort({
      sortField: e.sortField ?? undefined,
      sortOrder: normalized,
    });
  };

  const handleDelete = () => {
    confirmDialog({
      header: "Confirm Delete",
      message: "Delete this album permanently?",
      icon: "pi pi-exclamation-triangle",
      acceptLabel: "Delete",
      rejectLabel: "Cancel",
      acceptClassName: "p-button-danger",
      accept: async () => {
        try {
          setDeleting(true);
          await deleteAlbum(album?.id ?? -1).then(() => navigate("/albums"));
          toast.success("Album deleted.");
        } catch {
          toast.error("Failed to delete album.");
        } finally {
          setDeleting(false);
        }
      },
    });
  };

  if (!albumId) {
    return <Message severity="error" text="Invalid album id." />;
  }

  if (loadingAlbum) {
    return (
      <div className="min-h-[40vh] flex items-center justify-center gap-3 flex-col">
        <ProgressSpinner />
        <div className="text-[#6b7280] text-[0.95rem]">Loading album…</div>
      </div>
    );
  }

  if (albumError || !album) {
    return <Message severity="error" text={albumError ?? "Album not found."} />;
  }

  const canModify = !!user && user?.role === UserRoleEnum.ADMIN;

  const handleRefetch = () => {
    albumRefetch?.();
    refetchImage?.();
  };

  return (
    <div className="p-3">
      <div className="flex justify-between mb-3">
        <div>
          <Button
            label="Home"
            icon="pi pi-home"
            onClick={() => navigate("/")}
            severity="secondary"
            outlined
          />
        </div>
        <div className="flex justify-end gap-3">
          {canModify && (
            <div className="flex gap-3">
              <Button
                label="Edit"
                icon="pi pi-pencil"
                onClick={() => setEditAlbumDialogVisible(true)}
                severity="info"
                outlined
              />
              <Button
                label="Delete"
                icon={deleting ? "pi pi-spin pi-spinner" : "pi pi-trash"}
                onClick={handleDelete}
                severity="danger"
                outlined
              />
            </div>
          )}
          <Button
            label="Back"
            icon="pi pi-arrow-left"
            onClick={() => navigate(-1)}
            severity="secondary"
            outlined
          />
        </div>
      </div>

      <Card className="shadow-md" style={{ overflow: "hidden", borderRadius: 12 }}>
        <div className="flex gap-4 flex-col md:flex-row">
          <div style={{ width: 300, maxWidth: "100%" }}>
            <Image
              src={
                !loadingCover && coverExists
                  ? (coverSrc ?? undefined)
                  : undefined
              }
              alt={album.name}
              imageClassName="w-full"
              imageStyle={{ height: 280, objectFit: "cover" }}
            />
          </div>

          <div className="flex flex-col gap-3 w-fit">
            <div className="text-2xl font-semibold mb-2">{album.name}</div>

            {Array.isArray(album.artists) && album.artists.length > 0 && (
              <div className="flex items-center gap-2 mb-1 flex-wrap">
                <i className="pi pi-user text-gray-500" />
                {album.artists.map((a: ArtistType, i) => (
                  <span key={a.id} className="flex items-center gap-2">
                    <span
                      className="cursor-pointer text-[0.95rem] hover:underline"
                      onClick={() => navigate(`/artist/${a.id}`)}
                    >
                      {a.name}
                    </span>
                    {i < album.artists!.length - 1 && <span className="text-gray-400">·</span>}
                  </span>
                ))}
              </div>
            )}

            {album.year ? (
              <div className="text-gray-500 mb-2">Released {album.year}</div>
            ) : null}

            {Array.isArray(album.genres) && album.genres.length > 0 && (
              <div className="flex gap-2 flex-wrap mb-3">
                {album.genres.map((g: GenreType) => (
                  <Chip key={g.id ?? g.name} label={g.name} className="text-[0.85rem]" />
                ))}
              </div>
            )}

            <div className="flex gap-2 flex-wrap">
              {album.link && (
                <Button
                  label="Open Album Link"
                  icon="pi pi-external-link"
                  onClick={() => window.open(album.link, "_blank")}
                />
              )}
            </div>
          </div>
        </div>
      </Card>

      <Divider />

      <Card>
        <div className="flex items-center justify-between mb-2">
          <h2 className="m-0">Songs</h2>
        </div>

        <DataTable
          value={album.songs ?? []}
          rowHover
          stripedRows
          removableSort
          paginator
          rows={10}
          emptyMessage="No songs on this album."
          onRowClick={(row) => navigate(`/song/${row.data.id}`)}
        >
          <Column field="name" header="Title" sortable />

          <Column
            field="year"
            header="Year"
            body={(row: SongType) => row.year ?? "-"}
            sortable
          />
        </DataTable>
      </Card>

      <Divider />

      <Card>
        <div className="flex items-center justify-between mb-2">
          <h2 className="m-0">Reviews</h2>
          {reviewsError && <Message severity="error" text={reviewsError} />}
        </div>

        <DataTable
          value={reviews}
          rowHover
          stripedRows
          removableSort
          sortMode="multiple"
          paginator
          lazy
          totalRecords={total}
          rows={rows}
          first={page * rows}
          loading={loadingReviews}
          emptyMessage="No reviews for this album yet."
          onPage={handlePage}
          onSort={handleSort}
          sortField={sortField}
          sortOrder={sortOrder as 1 | 0 | -1 | null | undefined}
          onRowClick={(e) => openDialog(e.data as ReviewResponse)}
          rowClassName={() => ({ "cursor-pointer": true })}
        >
          <Column
            field="username"
            header="Reviewer"
            body={(row: ReviewResponse) => <strong>{row.username}</strong>}
            sortable
          />
          <Column
            field="grade"
            header="Rating"
            body={(row: ReviewResponse) => (
              <Rating value={row.grade} readOnly cancel={false} />
            )}
            sortable
          />
          <Column field="description" header="Description" />
          <Column
            field="creationDate"
            header="Created"
            body={(row: ReviewResponse) =>
              new Date(row.creationDate).toLocaleDateString("hr-HR")
            }
            sortable
          />
          <Column
            header="Type"
            body={() => <Tag value="Album" severity="info" />}
          />
        </DataTable>
      </Card>

      {dialogVisible && selectedReviewId !== undefined && (
        <ReviewDialog
          key={selectedReviewId}
          visible={dialogVisible}
          onHide={closeDialog}
          reviewId={selectedReviewId}
          reviewType="ALBUM"
          refetch={refresh}
        />
      )}

      {editAlbumDialogVisible && (
        <CreateAlbumDialog
          visible={editAlbumDialogVisible}
          setVisible={setEditAlbumDialogVisible}
          onCreated={handleRefetch}
          existingAlbumData={{
            albumId: albumId,
            formData: {
              name: album.name,
              year: album.year,
              cover: coverExists ? imageAsJsFile! : undefined,
              link: album.link,
              songIds: album.songs?.map((s) => s.id) ?? [],
              artistIds: album.artists?.map((ar) => ar.id) ?? [],
            },
          }}
        />
      )}

      <ConfirmDialog />
    </div>
  );
}

// mrp-vue/src/features/albums/AlbumDetails.page.vue
<template>
  <div v-if="isLoading" class="flex justify-center p-8">
    <ProgressSpinner />
  </div>
  <div v-else-if="album" class="flex flex-col gap-4 p-4">
    <ConfirmDialog />
    <div class="flex justify-between">
      <CreateAlbumDialog
        v-if="album"
        v-model="isEditDialogVisible"
        :album="album"
        @refetchAlbums="onEditSuccess"
      />
      <Button
        label="Home"
        icon="pi pi-home"
        class="p-button-outlined"
        @click="goHome"
      />

      <div class="flex gap-3">
        <Button
          v-if="isAdmin"
          label="Edit"
          icon="pi pi-pencil"
          class="p-button-outlined"
          severity="info"
          @click="onEditAlbum"
        />
        <Button
          v-if="isAdmin"
          label="Delete"
          icon="pi pi-trash"
          class="p-button-outlined"
          severity="danger"
          @click="onDeleteAlbum"
        />
        <Button
          label="Back"
          icon="pi pi-arrow-left"
          class="p-button-outlined"
          severity="secondary"
          @click="goBack"
        />
      </div>
    </div>

    <Card class="w-full">
      <template #content>
        <div class="flex gap-8">
          <div
            class="rounded-lg overflow-hidden w-[180px] h-[180px] shrink-0 bg-[#2a2a2a] flex items-center justify-center"
          >
            <Image
              v-if="displayImageUrl"
              :src="displayImageUrl"
              alt="Album Image"
              image-class="object-cover w-full h-full"
              class="w-full h-full"
            />
            <ProgressSpinner v-if="!displayImageUrl && isImageLoading" />
            <i
              v-else-if="!displayImageUrl"
              class="pi pi-image text-4xl text-gray-400"
            />
          </div>

          <div class="flex flex-col gap-4">
            <div class="flex flex-col gap-1">
              <h2 class="text-3xl font-bold m-0">{{ album.name }}</h2>
              <div class="flex items-center gap-2 text-gray-400 text-sm">
                <span class="flex items-center gap-1">
                  <i class="pi pi-calendar" /> {{ album.year }}
                </span>
                <span v-if="album.artists?.length">•</span>
                <span
                  v-if="album.artists?.length"
                  class="flex items-center gap-1"
                >
                  <i class="pi pi-user" />
                  <template v-for="(artist, index) in album.artists" :key="artist.id">
                    <span
                      class="cursor-pointer hover:underline"
                      @click.stop="router.push(`/artist/${artist.id}`)"
                    >{{ artist.name }}</span><span v-if="index < album.artists.length - 1"> • </span>
                  </template>
                </span>
                <span>•</span>
                <span class="flex items-center gap-1">
                  <i class="pi pi-headphones" />
                  {{ album.songs?.length || 0 }} songs
                </span>
              </div>
            </div>

            <div v-if="album.genres?.length">
              <h3 class="text-lg font-semibold mb-2">Genres</h3>
              <div class="flex flex-wrap gap-2">
                <Chip
                  v-for="genre in album.genres"
                  :key="genre.id"
                  :label="genre.name"
                />
              </div>
            </div>

            <div v-if="album.link">
              <Button
                label="Open External Link"
                icon="pi pi-external-link"
                @click="openLink(album.link)"
              />
            </div>
          </div>
        </div>
      </template>
    </Card>

    <Card v-if="album.songs?.length" class="w-full">
      <template #title>Songs</template>
      <template #content>
        <DataTable
          :value="album.songs"
          row-hover
          class="cursor-pointer"
          @row-click="(e) => onSongClick(e.data.id)"
        >
          <Column field="name" header="Name" sortable />
          <Column field="year" header="Year" sortable />
        </DataTable>
      </template>
    </Card>

    <Card class="w-full">
      <template #title>Reviews</template>
      <template #content>
        <DataTable
          v-if="albumReviews?.content?.length"
          :value="albumReviews.content"
          removableSort
        >
          <Column field="username" header="Reviewer" sortable />
          <Column field="grade" header="Rating" sortable>
            <template #body="slotProps">
              <Rating
                :model-value="slotProps.data.grade"
                readonly
                :cancel="false"
              />
            </template>
          </Column>
          <Column field="description" header="Description">
            <template #body="slotProps">
              <span class="line-clamp-2">{{ slotProps.data.description }}</span>
            </template>
          </Column>
          <Column field="creationDate" header="Created" sortable>
            <template #body="slotProps">
              {{ new Date(slotProps.data.creationDate).toLocaleDateString() }}
            </template>
          </Column>
          <Column field="type" header="Type" sortable>
            <template #body="slotProps">
              <Tag
                :value="'Album'"
                :severity="slotProps.data.type === 'ALBUM' ? 'success' : 'info'"
                rounded
              />
            </template>
          </Column>
        </DataTable>
        <div v-else class="text-gray-400">No reviews yet for this album.</div>
      </template>
    </Card>
  </div>
  <div v-else class="flex justify-center p-8">
    <p>Album not found.</p>
  </div>
</template>

<script setup lang="ts">
import {
  ProgressSpinner,
  Button,
  Card,
  Rating,
  Image,
  Chip,
  DataTable,
  Column,
  Tag,
  ConfirmDialog,
} from "primevue";
import { useConfirm } from "primevue/useconfirm";
import { useRoute, useRouter } from "vue-router";
import { computed, ref } from "vue";
import { useGetAlbum, useDeleteAlbum, CreateAlbumDialog, Role } from "@/features";
import { useGetFile, useAuthStore } from "@/shared";
import { storeToRefs } from "pinia";
import { useGetAlbumReviews } from "@/features/review";

const route = useRoute();
const router = useRouter();
const confirm = useConfirm();

const { user } = storeToRefs(useAuthStore());
const isAdmin = computed(() => user.value?.role === Role.ADMIN);

const albumId = computed(() => {
  const id = route.params.id;
  return id ? Number(id) : undefined;
});

const {
  data: album,
  isLoading: isAlbumLoading,
  refetch: refetchAlbum,
} = useGetAlbum(albumId);
const { data: albumReviews, isLoading: isReviewsLoading } =
  useGetAlbumReviews(albumId);

const { deleteAlbum } = useDeleteAlbum();

const isEditDialogVisible = ref(false);

const isLoading = computed(
  () => isAlbumLoading.value || isReviewsLoading.value,
);

const { fileUrl: displayImageUrl, isLoading: isImageLoading } = useGetFile(
  computed(() => album.value?.imageUrl),
);

const goHome = () => router.push("/");
const goBack = () => router.go(-1);
const openLink = (link: string) => window.open(link, "_blank");

const onEditAlbum = () => {
  isEditDialogVisible.value = true;
};

const onEditSuccess = () => {
  refetchAlbum();
};

const onSongClick = (songId: number) => {
  router.push(`/song/${songId}`);
};

const onDeleteAlbum = () => {
  if (!albumId.value) return;

  confirm.require({
    message: `Are you sure you want to delete "${album.value?.name}"?`,
    header: "Confirmation",
    icon: "pi pi-exclamation-triangle",
    rejectProps: {
      label: "Cancel",
      severity: "secondary",
      outlined: true,
    },
    acceptProps: {
      label: "Delete",
      severity: "danger",
    },
    accept: async () => {
      try {
        await deleteAlbum(albumId.value!);
        router.push("/albums");
      } catch (error) {
        console.error("Error deleting album:", error);
      }
    },
  });
};
</script>
