// mrp-react/src/shared/components/AlbumCard.tsx
import { useRef, useState } from "react";
import { Card } from "primereact/card";
import { Button } from "primereact/button";
import { Rating } from "primereact/rating";
import { Toast } from "primereact/toast";
import { Image } from "primereact/image";

import {
  AlbumReviewFormData,
  AlbumType,
  MAX_GENRES,
  truncate,
} from "@shared/utils";
import { useGetImage } from "../hooks/useGetImage";
import { submitAlbumReview } from "../../features/albums/hooks/submitAlbumReview.ts";
import { CreateAlbumReview } from "../../features/albums/CreateAlbumReview.tsx";
import { toast } from "./ToastContext.tsx";
import { useNavigate } from "react-router-dom";
import { Chip } from "primereact/chip";
import { Badge } from "primereact/badge";
const VITE_BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

interface Props {
  album: AlbumType;
  refetch?: () => void;
}

export default function AlbumCard({ album, refetch }: Props) {
  const [visibleDialog, setVisibleDialog] = useState(false);
  const navigate = useNavigate();
  const toastRef = useRef<Toast | null>(null);

  const {
    loading: loadingImage,
    exists: imageExists,
    image: image,
  } = useGetImage(
    album.imageUrl ? `${VITE_BACKEND_URL}${album.imageUrl}` : undefined,
  );

  const genres = album.genres ?? [];
  const visibleGenres = genres.slice(0, MAX_GENRES);
  const hasMoreGenres = genres.length > MAX_GENRES;
  const hiddenGenresTitle = genres
    .slice(MAX_GENRES)
    .map((g) => g.name)
    .join(", ");

  const songsCount = album.songs?.length ?? 0;

  const header = (
    <div className="w-full aspect-video overflow-hidden bg-[#f5f5f5] rounded-tl-[14px] rounded-tr-[14px]">
      {loadingImage ? (
        <div className="w-full h-full flex items-center justify-center">
          <i className="pi pi-spin pi-spinner" />
        </div>
      ) : (
        <Image
          src={imageExists && image ? image : undefined}
          imageClassName="w-full h-full object-cover block"
          className="block w-full h-full"
        />
      )}
    </div>
  );

  const handleSubmit = async (formData: AlbumReviewFormData) => {
    try {
      await submitAlbumReview(formData);
      toast.success("Successfully reviewed!");
      refetch?.();
    } catch {
      toast.error("Something went wrong.");
    }
  };

  return (
    <>
      <Card
        className="album-card shadow-md select-none cursor-pointer"
        style={{ width: 320, borderRadius: 14 }}
        header={header}
        onClick={() => navigate(`/album/${album.id}`)}
      >
        <div className="mt-2 px-4 pt-3 pb-4 flex flex-col gap-4">
          <div className="flex items-center justify-between gap-2">
            <h3 className="m-0 text-lg font-bold">{album.name}</h3>
            <span className="inline-flex items-center gap-[6px]">
              <i className="pi pi-headphones" />
              <Badge value={songsCount} />
            </span>
          </div>

          <div className="text-[#6b7280] text-[0.95rem]">Released {album.year}.</div>

          <div className="min-h-[44px] flex flex-wrap gap-2 mt-2">
            {visibleGenres.map((g) => (
              <Chip key={g.id} label={truncate(g.name, 10)} className="h-8" />
            ))}
            {hasMoreGenres && (
              <span
                title={hiddenGenresTitle}
                aria-label={`and ${genres.length - MAX_GENRES} more genres`}
              >
                …
              </span>
            )}
          </div>

          <div className="flex flex-col items-center gap-4 mb-2">
            {album.link && (
              <div className="mt-2">
                <Button
                  label="Open Album Link"
                  icon="pi pi-external-link"
                  onClick={(e) => {
                    e.stopPropagation();
                    window.open(album.link!, "_blank");
                  }}
                />
              </div>
            )}

            <div className="mt-2">
              {typeof album.grade === "number" ? (
                <Rating value={album.grade} cancel={false} />
              ) : (
                <Button
                  label="Review Album"
                  icon="pi pi-star"
                  onClick={(e) => {
                    e.stopPropagation();
                    setVisibleDialog(true);
                  }}
                />
              )}
            </div>

            {album.averageRating && (
              <div className="flex justify-center gap-2">
                Average:
                <i className="pi pi-star my-auto" />
                {`${album.averageRating} / 5`}
              </div>
            )}
          </div>
        </div>
      </Card>

      {visibleDialog && (
        <CreateAlbumReview
          visible={visibleDialog}
          name={album.name}
          albumId={album.id}
          onHide={() => setVisibleDialog(false)}
          onSubmit={handleSubmit}
        />
      )}

      <Toast ref={toastRef} />
    </>
  );
}

// mrp-vue/src/features/albums/AlbumCard.vue
<template>
  <Card
    class="w-[320px] h-[560px] rounded-lg! shadow-md! shadow-black cursor-pointer"
    @click="$emit('album-click', album)"
  >
    <template #header>
      <div
        class="w-full h-[180px] rounded-t-lg! object-cover bg-[#5f5f5f] flex justify-center items-center overflow-hidden"
      >
        <Image
          v-if="imageUrl"
          :src="imageUrl"
          image-class="object-cover w-full h-full"
          class="w-full h-full"
        />
        <ProgressSpinner v-else-if="isImageLoading" />
        <i v-else class="pi pi-image text-4xl" />
      </div>
    </template>

    <template #title>
      <div class="flex justify-between">
        <p class="m-0 p-0 text-xl font-bold truncate">{{ album.name }}</p>

        <div class="flex gap-2 items-center">
          <i class="pi pi-headphones" />
          <span class="text-sm">{{ album.songs?.length || 0 }}</span>
        </div>
      </div>
    </template>

    <template #subtitle>
      <div class="flex flex-col min-w-0">
        <span>Released {{ album.year }}.</span>
        <span v-if="album.artists?.length" class="text-sm truncate">
          by {{ album.artists.map((a) => a.name).join(", ") }}
        </span>
      </div>
    </template>

    <template #content>
      <div class="flex flex-col gap-4">
        <div v-if="album.genres?.length" class="flex gap-1 items-center overflow-hidden">
          <Chip
            v-for="genre in visibleGenres"
            :key="genre.id"
            :label="genre.name"
            class="w-fit h-2rem shrink-0"
          />
          <span v-if="hasMoreGenres" class="text-gray-400 text-sm shrink-0">...</span>
        </div>

        <div v-else>
          <p class="text-gray-400 h-2rem">No genres available.</p>
        </div>

        <div class="flex flex-col gap-4 justify-center items-center">
          <div>
            <Button
              v-if="album.link"
              label="Open Spotify / Youtube link"
              class="w-full"
              icon="pi pi-external-link"
              @click.stop="openLink"
            />

            <div v-else>
              <p class="text-gray-400 h-2rem">No external link available.</p>
            </div>
          </div>

          <div>
            <Button
              icon="pi pi-star"
              label="Review Album"
              class="w-fit"
              v-if="!album.grade"
              @click.stop="$emit('review', album)"
            />

            <div class="flex items-center my-2.5" v-else>
              <Rating :model-value="album.grade" readonly :cancel="false" />
            </div>
          </div>
        </div>

        <div
          class="flex justify-content-center gap-2"
          v-if="album.averageRating"
        >
          Average:
          <i class="pi pi-star my-auto" />
          {{ album.averageRating }} / 5
        </div>
      </div>
    </template>
  </Card>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { Card, Image, Button, Chip, Rating, ProgressSpinner } from "primevue";
import type { AlbumResponseDto } from "@/shared";
import { useGetFile } from "@/shared";

const props = defineProps<{
  album: AlbumResponseDto;
}>();

defineEmits<{
  (e: "review", album: AlbumResponseDto): void;
  (e: "album-click", album: AlbumResponseDto): void;
}>();

const visibleGenres = computed(() => props.album.genres?.slice(0, 3) ?? []);
const hasMoreGenres = computed(() => (props.album.genres?.length ?? 0) > 3);

const { fileUrl: imageUrl, isLoading: isImageLoading } = useGetFile(
  props.album.imageUrl,
);

const openLink = () => {
  if (props.album.link) {
    window.open(props.album.link, "_blank");
  }
};
</script>
