// mrp-react/src/features/albums/CreateAlbumDialog.tsx
import {
  Dispatch,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { Dialog } from "primereact/dialog";
import { toast } from "../../shared/components/ToastContext.tsx";
import {
  Controller,
  FormProvider,
  SubmitHandler,
  useForm,
} from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  AlbumCreateForm,
  albumCreateSchema,
  AlbumRequestData,
  truncate,
} from "@shared/utils";
import { InputText } from "primereact/inputtext";
import { FileUpload, FileUploadSelectEvent } from "primereact/fileupload";
import { Button } from "primereact/button";

import { useGetArtists } from "../artists/hooks/useGetArtists.ts";
import CreateLimitedArtistDialog from "../../shared/components/CreateLimitedArtistDialog.tsx";
import CreateLimitedSongDialog from "../../shared/components/CreateLimitedSongDialog.tsx";
import ArtistMultiSelect, {
  ArtistOption,
} from "../../shared/components/ArtistMultiSelect.tsx";
import SongMultiSelect, {
  SongOption,
} from "../../shared/components/SongMultiSelect.tsx";
import { useGetSongs } from "../songs/hooks/useGetSongs.tsx";
import { createAlbum, updateAlbum } from "./utils/helpers.tsx";

interface Props {
  visible: boolean;
  setVisible: Dispatch<boolean>;
  onCreated: () => void;
  existingAlbumData?: AlbumRequestData;
}

const EMPTY_FORM: AlbumCreateForm = {
  name: "",
  link: "",
  year: undefined as unknown as number,
  cover: undefined,
  songIds: [],
  artistIds: [],
};

export default function CreateAlbumDialog({
  visible,
  setVisible,
  onCreated,
  existingAlbumData,
}: Props) {
  const {
    artists,
    loading: artistsLoading,
    refetch: refetchArtists,
  } = useGetArtists();
  const { songs, loading: songsLoading, refetch: refetchSongs } = useGetSongs();

  const [artistDialogVisible, setArtistDialogVisible] = useState(false);
  const [songDialogVisible, setSongDialogVisible] = useState(false);

  const coverUploadRef = useRef<FileUpload>(null);
  const [coverName, setCoverName] = useState<string>("Choose");

  const handleArtistCreated = useCallback(() => {
    refetchArtists?.();
    setArtistDialogVisible(false);
  }, [refetchArtists]);

  const handleSongCreated = useCallback(() => {
    refetchSongs?.();
    setSongDialogVisible(false);
  }, [refetchSongs]);

  const artistOptions: ArtistOption[] = useMemo(
    () => (artists as ArtistOption[]) ?? [],
    [artists],
  );

  const songOptions: SongOption[] = useMemo(
    () =>
      (songs as SongOption[])?.map((s) => ({
        id: s.id,
        name: s.name,
        year: s.year,
      })) ?? [],
    [songs],
  );

  const methods = useForm<AlbumCreateForm>({
    resolver: zodResolver(albumCreateSchema),
    defaultValues: EMPTY_FORM,
  });

  const {
    handleSubmit,
    reset,
    control,
    formState: { errors, isSubmitting },
  } = methods;

  useEffect(() => {
    const nextDefaults: AlbumCreateForm = existingAlbumData
      ? {
          name: existingAlbumData.formData.name ?? "",
          link: existingAlbumData.formData.link ?? "",
          year: existingAlbumData.formData.year as number,
          cover: undefined,
          songIds: existingAlbumData.formData.songIds ?? [],
          artistIds: existingAlbumData.formData.artistIds ?? [],
        }
      : EMPTY_FORM;

    reset(nextDefaults);
    setCoverName(
      existingAlbumData?.formData.cover ? "Change Existing" : "Choose",
    );
  }, [existingAlbumData, visible, reset]);

  const onSubmit: SubmitHandler<AlbumCreateForm> = useCallback(
    async (data) => {
      const normalized: AlbumCreateForm = {
        ...data,
        songIds: Array.isArray(data.songIds) ? data.songIds : [],
        artistIds: Array.isArray(data.artistIds) ? data.artistIds : [],
      };

      try {
        if (existingAlbumData?.albumId) {
          await updateAlbum({
            albumId: existingAlbumData.albumId,
            formData: normalized,
          });
          toast.success("Album updated.");
        } else {
          await createAlbum({ formData: normalized });
          toast.success("Album created.");
        }
        reset(EMPTY_FORM);
        onCreated();
        setVisible(false);
      } catch {
        toast.error(
          existingAlbumData?.albumId
            ? "Failed to update album."
            : "Failed to create album.",
        );
      }
    },
    [existingAlbumData, onCreated, reset, setVisible],
  );

  return (
    <Dialog
      visible={visible}
      header={() =>
        existingAlbumData ? <div>Edit Album</div> : <div>Add an Album</div>
      }
      onHide={() => {
        reset(EMPTY_FORM);
        setVisible(false);
      }}
      resizable={false}
      draggable={false}
      className="md:w-[650px] w-[400px]"
    >
      <FormProvider {...methods}>
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="p-fluid flex flex-col gap-2"
        >
          <div className="field">
            <label htmlFor="name">Album Name</label>
            <Controller
              name="name"
              control={control}
              render={({ field }) => (
                <InputText
                  id="name"
                  value={field.value ?? ""}
                  onChange={(e) => field.onChange(e.target.value)}
                />
              )}
            />
            {errors.name && (
              <small className="p-error">{errors.name.message}</small>
            )}
          </div>

          <div className="flex justify-around gap-3">
            <div className="field">
              <label htmlFor="cover">Cover Image</label>
              <Controller
                name="cover"
                control={control}
                render={({ field }) => (
                  <FileUpload
                    ref={coverUploadRef}
                    name={field.name}
                    mode="basic"
                    customUpload
                    accept="image/*"
                    maxFileSize={5_000_000}
                    chooseLabel={coverName}
                    chooseOptions={{
                      icon: existingAlbumData ? "pi pi-sync" : "pi pi-plus",
                    }}
                    onSelect={(event: FileUploadSelectEvent) => {
                      if (event.files && event.files.length) {
                        const f = event.files[0];
                        field.onChange(f);
                        setCoverName(truncate(f.name));
                        coverUploadRef.current?.clear();
                      }
                    }}
                  />
                )}
              />
              {errors.cover && (
                <small className="p-error">{errors.cover.message}</small>
              )}
            </div>

            <div className="field">
              <label htmlFor="link">Link to Album</label>
              <Controller
                name="link"
                control={control}
                render={({ field }) => (
                  <InputText
                    id="link"
                    value={field.value ?? ""}
                    onChange={(e) => field.onChange(e.target.value)}
                  />
                )}
              />
              {errors.link && (
                <small className="p-error">{errors.link.message}</small>
              )}
            </div>
          </div>

          <div className="field">
            <label htmlFor="year">Year</label>
            <Controller
              name="year"
              control={control}
              render={({ field }) => (
                <InputText
                  id="year"
                  type="number"
                  value={field.value !== undefined ? String(field.value) : ""}
                  onChange={(e) => {
                    const v = e.target.value;
                    field.onChange(
                      v === "" ? (undefined as unknown as number) : Number(v),
                    );
                  }}
                  onBlur={field.onBlur}
                  name={field.name}
                  ref={field.ref}
                />
              )}
            />
            {errors.year && (
              <small className="p-error">{errors.year.message}</small>
            )}
          </div>

          <div className="field">
            <label htmlFor="songIdsSelect">Songs (optional)</label>
            <Controller
              name="songIds"
              control={control}
              render={({ field }) => (
                <SongMultiSelect
                  value={field.value ?? []}
                  options={songOptions}
                  loading={songsLoading}
                  onChange={(ids) => field.onChange(ids)}
                  onCreateNew={() => setSongDialogVisible(true)}
                  appendTo={
                    typeof document !== "undefined" ? document.body : undefined
                  }
                  className="w-full"
                />
              )}
            />
          </div>

          <div className="field mb-3">
            <label htmlFor="artistIdsSelect">Artists (optional)</label>
            <Controller
              name="artistIds"
              control={control}
              render={({ field }) => (
                <ArtistMultiSelect
                  value={field.value ?? []}
                  options={artistOptions}
                  loading={artistsLoading}
                  onChange={(ids) => field.onChange(ids)}
                  onCreateNew={() => setArtistDialogVisible(true)}
                  appendTo={
                    typeof document !== "undefined" ? document.body : undefined
                  }
                  className="w-full"
                />
              )}
            />
          </div>

          <Button
            type="submit"
            label="Submit"
            className="mt-3"
            loading={isSubmitting}
          />
        </form>
      </FormProvider>

      <CreateLimitedSongDialog
        visible={songDialogVisible}
        setVisible={setSongDialogVisible}
        onCreated={handleSongCreated}
      />
      <CreateLimitedArtistDialog
        visible={artistDialogVisible}
        setVisible={setArtistDialogVisible}
        onCreated={handleArtistCreated}
      />
    </Dialog>
  );
}

// mrp-vue/src/features/albums/CreateAlbumDialog.vue
<script setup lang="ts">
import { Button, Dialog, InputText, FileUpload, InputNumber, useToast } from "primevue";
import { useForm } from "vee-validate";
import { ModifiedMultiSelect } from "@/shared/components";
import { toTypedSchema } from "@vee-validate/zod";
import {
  type MultiSelectOptionType,
  albumCreateDefaultValues,
  albumCreateSchema,
  type AlbumResponseDto,
} from "@/shared";
import { useCreateAlbum, useUpdateAlbum, useGetAllSongs, useGetAllArtists } from "@/features";
import { computed, watch } from "vue";

const isDialogVisible = defineModel<boolean>();

const props = defineProps<{
  album?: AlbumResponseDto;
}>();

const emit = defineEmits<{
  (e: "refetchAlbums"): void;
}>();

const toast = useToast();
const { createAlbum, isLoading: isCreating } = useCreateAlbum();
const { updateAlbum, isLoading: isUpdating } = useUpdateAlbum();
const { data: songsData, isLoading: isSongsLoading } = useGetAllSongs();
const { data: artistsData, isLoading: isArtistsLoading } = useGetAllArtists();

const isSubmitting = computed(() => isCreating.value || isUpdating.value);

const artistOptions = computed<MultiSelectOptionType[]>(() => {
  return (
    artistsData.value?.map((artist) => ({
      label: artist.name,
      value: artist.id,
    })) || []
  );
});

const songOptions = computed<MultiSelectOptionType[]>(() => {
  return (
    songsData.value?.map((song) => ({
      label: song.name,
      value: song.id,
    })) || []
  );
});

const validationSchema = toTypedSchema(albumCreateSchema);

const initialValues = computed(() => {
  if (props.album) {
    return {
      name: props.album.name,
      year: props.album.year,
      link: props.album.link,
      songIds: props.album.songs?.map((s) => s.id) || [],
      artistIds: props.album.artists?.map((a) => a.id) || [],
      cover: undefined,
    };
  }
  return albumCreateDefaultValues;
});

const { handleSubmit, defineField, errors, resetForm } = useForm({
  validationSchema,
  initialValues: initialValues.value,
  keepValuesOnUnmount: false,
});

watch(
  initialValues,
  (newValues) => {
    resetForm({ values: newValues });
  },
  { immediate: true },
);

const [name] = defineField("name");
const [link] = defineField("link");
const [year] = defineField("year");
const [cover] = defineField("cover");
const [songIds] = defineField("songIds");
const [artistIds] = defineField("artistIds");

const onSubmit = handleSubmit(async (values) => {
  let result;
  if (props.album) {
    result = await updateAlbum(props.album.id, values);
  } else {
    result = await createAlbum(values);
  }

  if (result) {
    toast.add({ severity: "success", summary: props.album ? "Album updated successfully" : "Album added successfully" });
    isDialogVisible.value = false;
    emit("refetchAlbums");
  }
});
</script>

<template>
  <Dialog
    modal
    class="w-160"
    v-model:visible="isDialogVisible"
    :header="props.album ? 'Edit album' : 'Add an album'"
    :draggable="false"
  >
    <form @submit="onSubmit" class="flex flex-col gap-3 w-full">
      <div class="flex flex-col gap-2">
        <label>Album Name</label>
        <InputText v-model="name" type="text" :invalid="!!errors.name" />
        <small v-if="errors.name" class="text-red-500">{{ errors.name }}</small>
      </div>

      <div class="flex flex-col w-fit gap-3">
        <div class="flex flex-col gap-2">
          <label for="cover">Cover Image</label>
          <FileUpload
            label="Choose"
            mode="basic"
            icon="pi pi-plus"
            accept="image/*"
            :invalid="!!errors.cover"
            @select="(e) => (cover = e.files[0])"
          />
          <small v-if="errors.cover" class="text-red-500">{{
            errors.cover
          }}</small>
        </div>
      </div>

      <div class="flex flex-col gap-2">
        <label for="link">Link to album</label>
        <InputText
          id="link"
          v-model="link"
          type="text"
          :invalid="!!errors.link"
        />
        <small v-if="errors.link" class="text-red-500">{{ errors.link }}</small>
      </div>

      <div class="flex flex-col gap-2">
        <label for="year">Year</label>
        <InputNumber
          id="year"
          v-model="year"
          :use-grouping="false"
          :invalid="!!errors.year"
        />
        <small v-if="errors.year" class="text-red-500">{{ errors.year }}</small>
      </div>

      <div class="flex flex-col gap-2">
        <label>Songs (optional)</label>
        <ModifiedMultiSelect
          :options="songOptions"
          :loading="isSongsLoading"
          v-model="songIds"
          :invalid="!!errors.songIds"
        />
        <small v-if="errors.songIds" class="text-red-500">{{
          errors.songIds
        }}</small>
      </div>

      <div class="flex flex-col gap-2">
        <label>Artists (optional)</label>
        <ModifiedMultiSelect
          :options="artistOptions"
          :loading="isArtistsLoading"
          v-model="artistIds"
          :invalid="!!errors.artistIds"
        />
        <small v-if="errors.artistIds" class="text-red-500">{{
          errors.artistIds
        }}</small>
      </div>

      <div class="flex flex-col gap-2 w-full items-end">
        <Button
          type="submit"
          :label="props.album ? 'Update album' : 'Add new album'"
          :icon="props.album ? 'pi pi-check' : 'pi pi-plus'"
          :loading="isSubmitting"
        />
      </div>
    </form>
  </Dialog>
</template>
