// mrp-vue/src/features/songs/SongCard.vue
<template>
  <Card
    class="w-[320px] h-[560px] rounded-lg! shadow-md! shadow-black cursor-pointer"
    @click="$emit('song-click', song)"
  >
    <template #header>
      <div
        class="w-full h-[180px] rounded-t-lg! object-cover bg-[#5f5f5f] flex justify-center items-center overflow-hidden"
      >
        <Image
          v-if="imageUrl"
          :src="imageUrl"
          image-class="object-cover w-full h-full"
          class="w-full h-full"
        />
        <ProgressSpinner v-else-if="isImageLoading" />
        <i v-else class="pi pi-image text-4xl" />
      </div>
    </template>

    <template #title>
      <div class="flex justify-between gap-2 min-w-0">
        <p class="m-0 p-0 truncate min-w-0">{{ song.name }}</p>
        <Tag v-if="song.grade" value="Reviewed" />
      </div>
    </template>

    <template #subtitle>Released {{ song.year }}.</template>

    <template #content>
      <div class="flex flex-col gap-4">
        <div v-if="song.genres?.length" class="flex gap-1 items-center overflow-hidden">
          <Chip
            v-for="genre in visibleGenres"
            :key="genre.id"
            :label="genre.name"
            class="w-fit h-2rem shrink-0"
          />
          <span v-if="hasMoreGenres" class="text-gray-400 text-sm shrink-0">...</span>
        </div>

        <div v-else>
          <p class="text-gray-400 h-2rem">No genres available.</p>
        </div>

        <div class="flex flex-col gap-4 justify-center items-center">
          <audio v-if="audioUrl" controls :src="audioUrl" @click.stop />
          <ProgressSpinner v-else-if="isAudioLoading" style="width: 40px; height: 40px" />
          <div v-else>
            <p class="text-gray-400 h-2rem">No audio file available.</p>
          </div>

          <div>
            <Button
              v-if="props.song.link"
              label="Open Spotify / Youtube link"
              class="w-full"
              icon="pi pi-external-link"
              @click.stop="openLink"
            />

            <div v-else>
              <p class="text-gray-400 h-2rem">No external link available.</p>
            </div>
          </div>

          <div>
            <Button
              icon="pi pi-star"
              label="Review Song"
              class="w-fit"
              v-if="!props.song.grade"
              @click.stop="$emit('review', props.song)"
            />

            <div class="flex items-center my-2.5" v-else>
              <Rating
                :model-value="props.song.grade"
                readonly
                :cancel="false"
              />
            </div>
          </div>
        </div>

        <div
          class="flex justify-content-center gap-2"
          v-if="song.averageRating"
        >
          Average:
          <i class="pi pi-star my-auto" />
          {{ song.averageRating }} / 5
        </div>
      </div>
    </template>
  </Card>
</template>

<script setup lang="ts">
import { computed } from "vue";
import {
  Card,
  Image,
  Button,
  Tag,
  Chip,
  Rating,
  ProgressSpinner,
} from "primevue";
import type { SongResponse } from "@/shared";
import { useGetFile } from "@/shared";

const props = defineProps<{
  song: SongResponse;
}>();

defineEmits<{
  (e: "review", song: SongResponse): void;
  (e: "song-click", song: SongResponse): void;
}>();

const visibleGenres = computed(() => props.song.genres?.slice(0, 3) ?? []);
const hasMoreGenres = computed(() => (props.song.genres?.length ?? 0) > 3);

const { fileUrl: imageUrl, isLoading: isImageLoading } = useGetFile(
  props.song.imageUrl,
);
const { fileUrl: audioUrl, isLoading: isAudioLoading } = useGetFile(
  props.song.fileUrl,
);

const openLink = () => {
  if (props.song.link) {
    window.open(props.song.link, "_blank");
  }
};
</script>

// mrp-react/src/shared/components/SongCard.tsx
import { useState } from "react";
import { Card } from "primereact/card";
import { Button } from "primereact/button";
import { Chip } from "primereact/chip";
import { Rating } from "primereact/rating";
import { Tag } from "primereact/tag";
import { Image } from "primereact/image";

import {
  MAX_GENRES,
  SongReviewFormData,
  SongType,
  truncate,
} from "@shared/utils";
import { useGetImage } from "../hooks/useGetImage";
import { useSongAudio } from "../hooks/useSongAudio";
import { submitSongReview } from "../../features/songs/hooks/submitSongReview.ts";
import { CreateSongReview } from "../../features/songs/CreateSongReview.tsx";
import { toast } from "./ToastContext.tsx";
import { useNavigate } from "react-router-dom";
const VITE_BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

interface Props {
  song: SongType;
  refetch: () => void;
}

export default function SongCard({ song, refetch }: Props) {
  const [visibleDialog, setVisibleDialog] = useState(false);
  const navigate = useNavigate();

  const genres = song.genres ?? [];
  const visibleGenres = genres.slice(0, MAX_GENRES);
  const hasMoreGenres = genres.length > MAX_GENRES;
  const hiddenGenresTitle = genres
    .slice(MAX_GENRES)
    .map((g) => g.name)
    .join(", ");

  const {
    loading: loadingImage,
    exists: imageExists,
    image: image,
  } = useGetImage(`${VITE_BACKEND_URL}${song.imageUrl}`);

  const {
    loading: loadingAudio,
    exists: audioExists,
    url: audioUrl,
  } = useSongAudio(song.id, song.fileUrl);

  const handleSubmit = async (formData: SongReviewFormData) => {
    try {
      await submitSongReview(formData);
      toast.success(`Successfully reviewed ${song.name}`);
      refetch();
    } catch {
      toast.error("Something went wrong");
    }
  };

  const header = (
    <div className="w-full h-[180px] bg-[#f5f5f5] overflow-hidden">
      {loadingImage ? (
        <div className="w-full h-full flex items-center justify-center">
          <i className="pi pi-spin pi-spinner" />
        </div>
      ) : (
        <Image
          src={imageExists && image ? image : undefined}
          imageStyle={{ width: "100%", height: 180, objectFit: "cover" }}
        />
      )}
    </div>
  );

  return (
    <>
      <Card
        className="song-card shadow-md select-none cursor-pointer"
        style={{
          width: 320,
          height: 560,
          display: "flex",
          flexDirection: "column",
        }}
        header={header}
        onClick={() => navigate(`/song/${song.id}`)}
      >
        <div className="flex flex-col px-5 py-5 flex-1">
          <div className="flex items-center justify-between min-h-[40px] mb-1">
            <h3 className="m-0 text-xl leading-tight truncate flex-1 min-w-0">
              {song.name}
            </h3>
            <Tag
              value="Reviewed"
              severity="success"
              style={{ visibility: song.grade ? "visible" : "hidden" }}
            />
          </div>

          <div className="min-h-[22px] text-[#6b6b6b]">
            Released {song.year}.
          </div>

          <div className="min-h-[44px] flex flex-wrap gap-2 mt-2">
            {visibleGenres.map((g) => (
              <Chip key={g.id} label={truncate(g.name, 10)} className="h-8" />
            ))}
            {hasMoreGenres && (
              <span
                title={hiddenGenresTitle}
                aria-label={`and ${genres.length - MAX_GENRES} more genres`}
              >
                …
              </span>
            )}
          </div>

          <div className="flex-1" />

          <div className="flex flex-col gap-[25px] pt-2">
            <div className="h-[42px] flex items-center">
              {loadingAudio ? (
                <i className="pi pi-spin pi-spinner" />
              ) : audioExists && audioUrl ? (
                <audio controls src={audioUrl} className="w-full" />
              ) : (
                <div className="w-full h-full">No audio file available.</div>
              )}
            </div>

            <div className="h-[44px] flex items-center justify-center">
              <Button
                label="Open Spotify / Youtube link"
                icon="pi pi-external-link"
                onClick={(e) => {
                  e.stopPropagation();
                  if (song.link) window.open(song.link, "_blank");
                }}
                style={{ visibility: song.link ? "visible" : "hidden" }}
              />
            </div>

            <div className="h-[44px] flex items-center justify-center">
              {song.grade ? (
                <Rating value={song.grade} cancel={false} />
              ) : (
                <Button
                  label="Review Song"
                  icon="pi pi-star"
                  onClick={(e) => {
                    e.stopPropagation();
                    setVisibleDialog(true);
                  }}
                />
              )}
            </div>

            {song.averageRating && (
              <div className="flex justify-center gap-2">
                Average:
                <i className="pi pi-star my-auto" />
                {`${song.averageRating} / 5`}
              </div>
            )}
          </div>
        </div>
      </Card>

      <CreateSongReview
        visible={visibleDialog}
        name={song.name}
        songId={song.id}
        onHide={() => setVisibleDialog(false)}
        onSubmit={handleSubmit}
      />
    </>
  );
}
